const Audio = [

  {
    id: 100,
    order: '1',
    type: 'audio',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '642376728',
    thumb_url: 'https://i1.sndcdn.com/artworks-000557759277-nwur66-t500x500.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','Eeva Bolin','K-Play'],
    title: '#129 Eeva Bolin - Ny organisation för kultur i grundskola och förskola',
    short_title: 'Short example title...',
    collaborators: ['Musikens Hus, Göteborg','Grundskoleförvaltningen','Förskoleförvaltningen'],
    cast: ['Eeva Bolin'],
    date: '2019-05-29',
  },
  {
    id: 99,
    order: '1',
    type: 'audio',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '642375006',
    thumb_url: 'https://i1.sndcdn.com/artworks-000557757795-foa5ie-t500x500.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','Åsa Jansson','K-Play'],
    title: '#128 Åsa Jansson – Regionala arrangörsstödet för barn & unga - kulturkatalogen väst',
    short_title: 'Short example title...',
    collaborators: ['kulturkatalogen väst','Musikens Hus, Göteborg'],
    cast: ['Åsa Jansson'],
    date: '2019-05-29',
  },
  {
    id: 98,
    order: '1',
    type: 'audio',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '642369729',
    thumb_url: 'https://i1.sndcdn.com/artworks-000557753274-9ko0m8-t500x500.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','Ida Kaivola','K-Play'],
    title: '#127 Ida Kaivola - Kulturstöd och regler för utjämningsbidraget i Göteborg',
    short_title: 'Short example title...',
    collaborators: ['Musikens Hus, Göteborg'],
    cast: ['Ida Kaivola'],
    date: '2019-05-29',
  },
  {
    id: 97,
    order: '1',
    type: 'audio',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '641768196',
    thumb_url: 'https://i1.sndcdn.com/artworks-000557176050-0clbo8-t500x500.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','Madeleine Ekman','Peter Possne','Jenny Luukkonen','K-Play'],
    title: '#126 SFI & Film i Väst – filmfinansieringens möjligheter & utmaningar',
    short_title: 'Short example title...',
    collaborators: ['SFI & Film i Väst','Wift Väst','Kulturakademin'],
    cast: ['Madeleine Ekman','Peter Possne','Jenny Luukkonen'],
    date: '2019-07-19',
  },
  {
    id: 96,
    order: '1',
    type: 'audio',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '639535935',
    thumb_url: 'https://i1.sndcdn.com/artworks-000555087723-0k2w43-t500x500.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','Åsa Söderberg','K-Play','RePublik','Kultur i Väst'],
    title: '#125 Åsa Söderberg – 12 års erfarenhet av publikutveckling på Skånes Dansteater',
    short_title: 'Short example title...',
    collaborators: ['RePublik','Kultur i Väst'],
    cast: ['Åsa Söderberg'],
    date: '2019-05-21',
  },
  {
    id: 95,
    order: '1',
    type: 'audio',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '639016008',
    thumb_url: 'https://i1.sndcdn.com/artworks-000554510037-rxwixc-t500x500.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','Ida Kaivola','K-Play'],
    title: '#124 Fading Lights - The Transition From Candle To Led with Chris Van Goethem (LIVE: 2019-05-06)',
    short_title: 'Short example title...',
    collaborators: ['YRGO','Folkteatern','Svensk Teaterteknisk Förening'],
    cast: ['Chris Van Goethem'],
    date: '2019-06-19',
  },
];

module.exports = Audio