const Audio = [

  {
    id: 81,
    order: '1',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '5s3bicmZ3hYoDSvssGKEUS',
    thumb1: 'https://i.scdn.co/image/e280413685d7acd08f45a14bfd995c7759fd9090',
    thumb2: 'https://i.scdn.co/image/1c67134c021683d54abca2a1901723d24f6519ee',
    thumb3: 'https://i.scdn.co/image/a190f3f32b164f2da87b185a3c20bd20ef12bd1c',
    description: 'SCENKONSTBIENNALEN 2019: KOMPETENSUTVECKLING FÖR SKÅDESPELARE – NU OCH I FRAMTIDEN Arrangeras av: TeaterAlliansen Vilken kompetensutveckling erbjuds skådespelare idag? Hur ser framtiden ut? Ställer ny teknik och nya former av berättande krav på en ny typ av kunskap? Vilka behov finns – vad efterfrågar skådespelarna och vad tycker arbetsgivarna behövs. Det är några av de frågor som kommer att lyftas under seminariet. Medverkande: Tobias Aspelin, skådespelare Johanna Selander, konstnärlig ledare, Ögonblicksteatern Petra Brylander, teaterchef, Uppsala Stadsteater Moderator: Anna Carlson, skådespelare, f.d. ordförande Teaterförbundet Resultatredovisning av enkätundersökning: http://teateralliansen.se/wp-content/uploads/2019/05/Presentation-TeaterAlliansen-Kompetensbehov-2019-kopia.pdf INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED TEATERALLIANSEN UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: KOMPETENSUTVECKLING FÖR SKÅDESPELARE...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','panelsamtal','audio'],
    title: '#100 Panelsamtal - Kompetensutveckling för skådespelare nu och i framtiden (LIVE: 2019-05-15)',
    short_title: '#100 Panelsamtal - Kompetensutveckling',
    collaborators: ['TeaterAlliansen','Scenkonstbiennalen'],
    cast: ['Tobias Aspelin','Johanna Selander','Petra Brylander','Anna Carlson'],
    date: '2019-05-22',
  },
  {
    id: 69,
    order: '2',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '25yyjVIRsVKfk2PTkKSNGP',
    thumb1: 'https://i.scdn.co/image/0f9b76ff398f09f42f5cfedba477d46b7fc169a3',
    thumb2: 'https://i.scdn.co/image/8c03cc7ccabee49fdc80b158cf21b910c01f1e8a',
    thumb3: 'https://i.scdn.co/image/fc0bac5827aed7845150c872b73720d0ba1dd719',
    description: 'SCENKONSTBIENNALEN 2019: DANSARE - OAVSETT VILLKOR? Arrangeras av: Teaterförbundets Dansavdelning Hur påverkar rådande villkor verksamma aktörer? Hur ser vardagen ut? Vilka konkreta åtgärder skulle hjälpa? Hur bråttom är det? Teaterförbundets Dansavdelning lyfter fram aktörer från den fria dansscenen, vars situation är som mest prekär. Scenkonstbiennalen är ett viktigt tillfälle för dessa röster att höras, för att sprida viktig kunskap från fältet. Seminariet är en handuträckning att vara med i samtalet om dansens framtid. Vi behöver prata om villkoren för danskonstnärernas verksamheter, och om dansens betydelse och omätbara värde. Hur kan Dans fortsätta vara en vital konstform, och samtidigt en konstform med skäliga villkor och värdiga arbetsförhållanden? Medverkande: Lotta Gahrton Tyra Wigg Hannah Karlsson Moderator: Christine Brorsson INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED TEATERFÖRBUNDETS DANSAVDELNING UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: DANSARE - OAVSETT VILLKOR?...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','dansare','scenkonstbiennalen','audio'],
    title: '#101 Dansare – oavsett villkor? (LIVE: 2019-05-15)',
    short_title: '#101 Dansare – oavsett villkor?',
    collaborators: ['Teaterförbundets Dansavdelning','Scenkonstbiennalen'],
    cast: ['Lotta Gahrton','Tyra Wigg','Hannah Karlsson','Christine Brorsson'],
    date: '2019-05-22',
  },
  {
    id: 96,
    order: '1',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '1HN649bRu9WmuWm1qEWWEU',
    thumb1: 'https://i.scdn.co/image/18cc3148a75daf9ea41c645b0d656175451fc99b',
    thumb2: 'https://i.scdn.co/image/9d6034df626f6d1f31652a23d8e627b7f2d6a57b',
    thumb3: 'https://i.scdn.co/image/3ad7e667a658fb21ea50f80b6b4e005fae949fdb',
    description: 'SCENKONSTBIENNALEN 2019: SCENKONSTEN OCH KLIMATET: KLIMATFRÅGAN UR ETT KONSTNÄRLIGT OCH PUBLIKT PERSPEKTIV Arrangeras av: Institutionen för scenkonst på StDH/ Stockholms konstnärliga högskola och Riksteatern Vi står mitt uppe i stora förändringar och framtiden är oviss. Osäkerheten ökar och temperaturen stiger. Vad gör scenkonsten när världen håller på att gå under? Seminariet samlar scenkonstnärer och klimatforskare i ett samtal med varandra och med publiken om nya former av samarbeten och berättelser. Kan dialogen mellan konst och vetenskap generera nya dramaturgiska strukturer och former för gestaltning? Hur kan dialogen utökas till att även omfatta publiken och det omgivande samhället? Hur skapar vi hållbarhet i våra produktioner? Seminariet syftar till att skapa dialog kring klimatfrågan ur ett konstnärligt och publikt perspektiv samt att bygga nätverk och broar mellan konst och vetenskap. Medverkande: Måns Lagerlöf, kanslichef, Naturskyddsföreningen Lisa Fernström, regissör Anna Kaijser, forskningssekreterare på miljöavdelningen, med särskilt fokus på klimat, Formas Åsa Johannisson, regissör Moderator: Birgitta Englin, Senior rådgivare Global Utmaning INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED INSTITUTIONEN FÖR SCENKONST PÅ STDH/ STOCKHOLMS KONSTNÄRLIGA HÖGSKOLA OCH RIKSTEATERN UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: SCENKONSTEN OCH KLIMATET...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','klimatet','scenkonstbiennalen','audio'],
    title: '#102 Scenkonsten & klimatet – ett konstnärligt & publikt perspektiv (LIVE: 2019-05-16)',
    short_title: '#102 Scenkonsten & klimatet',
    collaborators: ['Institutionen för scenkonst','Riksteatern'],
    cast: ['Måns Lagerlöf','Lisa Fernström','Anna Kaijser','Åsa Johannisson','Birgitta Englin'],
    date: '2019-05-24',
  },
  {
    id: 71,
    order: '3',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '7IwQiXn3dLAhkiS6mJpCUb',
    thumb1: 'https://i.scdn.co/image/69f95fd4a746f750c6e6df7c66ab8085389d8a79',
    thumb2: 'https://i.scdn.co/image/92bf764735b62e9108e78897c22b49241183fe7c',
    thumb3: 'https://i.scdn.co/image/6b87d1b32b79b36a8fcc9e7504a239182a4c4383',
    description: 'SCENKONSTBIENNALEN 2019: DIRECTING AND ACTING FOR INTIMATE SCENES Organizer: Swedish union of Directors an Actors Department, Teaterförbundet and TeaterAlliansen Ita O´Brien talks about her work as Intimacy Coordinator and Intimacy on set guidelines. How to use these guidelines to create a safe, mutual and predictable situation in scenes with intimacy, nudity and sex on stage. Lecturer: Ita O’Brien, Intimacy Coordinator and Movement Director Produced for K-PLAY by Kulturakademin in collaboration with Swedish Union of Directors and Actors Department, Teaterförbundet and TeaterAlliansen under Scenkonstbiennalen 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: DIRECTING AND ACTING FOR INTIMATE SCENES Organizer...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','directing','acting','audio'],
    title: '#103 Ita O’Brien – Directing and Acting for Intimate Scenes (LIVE: 2019-05-16)',
    short_title: '#103 Ita O’Brien – Directing and Acting',
    collaborators: ['Swedish union of Directors','Actors Department','Teaterförbundet','TeaterAlliansen','Scenkonstbiennalen'],
    cast: ['Ita O’Brien'],
    date: '2019-05-24',
  },
  {
    id: 75,
    order: '4',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '6yDGSZ2PCkUIDm7WH7pQTp',
    thumb1: 'https://i.scdn.co/image/be69c59bad5355305adba570a6a3a67b3ad97bf2',
    thumb2: 'https://i.scdn.co/image/5b873def884a2b9ab6d3657e99a2a6083487089a',
    thumb3: 'https://i.scdn.co/image/184cece9fd215b7f98be93b61293a5653d3a74d8',
    description: 'SCENKONSTBIENNALEN 2019: NÄR REPSALEN FÅR LIV Arrangeras av: Teater Halland Vad är det mer än spelregler och medvetenhet om maktstrukturer som gör att vi arbetar bra tillsammans? Finns det andra mekanismer, utöver ett schysst arbetsklimat, som gör att repsalen får liv? I detta seminarium försöker vi få fatt i det ogreppbara att skapa konst och vad det är i processen som gör oss kreativa tillsammans. Finns avgörande komponenter för goda repetitionsarbeten eller handlar allt bara om personkemi, humor, teatersyn eller sätt att se på världen? I ett personligt och öppenhjärtigt samtal delar paneldeltagarna med sig av erfarenheter av när de funkat bra och dåligt på jobbet. Tillsammans med publiken reflekterar vi kring vad det är som gör att vi ibland är med om det mest fantastiska. Medverkande skådespelare: Amed Bozan, student StDH Petter Heldt, Teater Halland Mia Höglund Melin, Göteborgs Stadsteater, lektor i skådespeleri HSM Peter Lorentzon, Regionteater Väst Gisela Nilsson, Teater Västernorrland Medverkande regissörer: Carolina Frände, Kulturhuset Skärholmen Olof Hansson, Kulturhuset Stadsteatern Johan Paus, student StdH Anna Pettersson, Strindbergs Intima Teater Samtalsledare: Anna Sjövall, regissör och konstnärlig ledare Teater Halland INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED TEATER HALLAND UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: NÄR REPSALEN FÅR LIV...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','panelsamtal','kreativitet','audio'],
    title: '#104 När repsalen får liv – Panelsamtal om kreativitet och spelregler (LIVE: 2019-05-15)',
    short_title: '#104 När repsalen får liv – Panelsamtal om kreativitet',
    collaborators: ['Teater Halland','Scenkonstbiennalen'],
    cast: ['Anna Sjövall'],
    date: '2019-05-27',
  },
  {
    id: 90,
    order: '5',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '2RuR9oa8dk0PEroCtsu16s',
    thumb1: 'https://i.scdn.co/image/925964055e8f642794efc5127cbdd02c55582c37',
    thumb2: 'https://i.scdn.co/image/4de7972de4a425860b27a10044cfd0c6bf74ab01',
    thumb3: 'https://i.scdn.co/image/15ba970f0056c25ce615e5dd2de3088d237ec905',
    description: 'SCENKONSTBIENNALEN 2019: EKODESIGNDIREKTIVET FÖR LJUSET ÄR SNART ETT FAKTUM! MEN GÅR NÅGOT KONSTNÄRLIGT FÖRLORAT NU? Arrangeras av: Svenska Ljussättareföreningen - SLF 2021 kommer det nya Ekodirektivet för ljus att träda i kraft. Bland landets ljussättare har detta uppmärksammats främst genom att en hel del av de traditionella halogenlamporna har fått stryka på foten till förmån för det nya LED-ljuset som drar mindre energi men som ännu inte är helt fulländat ur ett tekniskt perspektiv t ex i hur färg återges i scenografi och kostymer. Samtidigt byter en rad teatrar ut sin utrustning mot den nya typen av ljuskällor. Har vi konstnärligt gått miste om något och är det så mycket att bråka om, nu när vi alla ska hjälpas åt för att rädda planeten? I ett samtal om design och utveckling försöker vi sätt in detta problem i sitt sammanhang. Medverkande: Emma Weil, chef för utvecklingssektionen på Dramaten Mattias Fransson, ljusdesigner Mauritz de Vries, ljusdesigner Samtalsledare: Anders Larsson, ordförande i Svenska Ljussättareföreningen – SLF INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED SVENSKA LJUSSÄTTAREFÖRENINGEN - SLF UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: EKODESIGNDIREKTIVET FÖR LJUSET ÄR SNART ETT FAKTUM!...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','panelsamtal','kreativitet','audio'],
    title: '#105 Ekodesigndirektivet för ljuset – men går något konstnärligt förlorat (LIVE: 2019-05-16)',
    short_title: '#105 Ekodesigndirektivet för ljuset',
    collaborators: ['Svenska Ljussättareföreningen - SLF 2021','Scenkonstbiennalen'],
    cast: ['Emma Weil','Mattias Fransson','Mauritz de Vries','Anders Larsson'],
    date: '2019-05-27',
  },
  {
    id: 79,
    order: '6',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '5wg06lX9kKAxmgDbeV0q8J',
    thumb1: 'https://i.scdn.co/image/4a35cca2a8ee0aaa10f7e6879fad81b66cfb7726',
    thumb2: 'https://i.scdn.co/image/bac64929988445d2cf543031d255813f5eedcbf9',
    thumb3: 'https://i.scdn.co/image/db5c07fac1e9a738763fe9ac14ec4e51aec8477b',
    description: 'SCENKONSTBIENNALEN 2019: AVATARER I ENSEMBLEN Arrangeras av: Cabaret Electrique / Kafkas Arkiv Kan realtidsstyrda digitala skådespelare bli en del av framtidens ensemble? Cabaret Electrique har undersökt samspelet mellan animationsteknik och teater för att hitta nya sceniska uttryck. Efter flera år av workshops och forskningsprojekt med KTH, Dramaten och STDH satte vi upp föreställningen Kafkas Arkiv i reaktorhallen, där levande animationer styrda av motion capture och VR blandades med skådespelare i Kafkas klaustrofobiska värld. Att blanda animerade och riktiga skådespelare på scen bjuder på många möjligheter till ny gestaltning, men också på tekniska och processmässiga utmaningar. Hur kan teaterns improvisatoriska och direkta sätt att arbeta kombineras med animationens fyrkantigare process? Och hur kan ny animationsteknik bidra med att skapa förhöjda sceniska uttryck från filmens värld utan att förlora teaterns här och nu? Vi vill dela med oss av våra praktiska erfarenheter kring vår forskning och våra val i dessa frågor. Inom film- och spelindustrin fortsätter man att flytta fram gränsen för hur åskådaren kan känna sig delaktig. För den yngre publiken som vuxit upp på en digital arena finns andra förväntningar kring hur historier berättas och upplevs. Så hur kan scenkonsten inspireras av avancerad teknik och ändå fortsätta att vara unikt relevant för publiken och dess samtid? Medverkande: Filip Alexanderson, skådespelare och regissör (Cabaret Electrique / Kafkas Arkiv) INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED CABARET ELECTRIQUE / KAFKAS ARKIV UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: AVATARER I ENSEMBLEN...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','avatarer','audio'],
    title: '#106 Avatarer i ensemblen – animationer och digital teknik på scen (LIVE: 2019-05-16)',
    short_title: '#106 Avatarer i ensemblen -',
    collaborators: ['Cabaret Electrique / Kafkas Arkiv','Scenkonstbiennalen'],
    cast: ['Filip Alexanderson'],
    date: '2019-06-03',
  },
  {
    id: 70,
    order: '7',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '22kCuViddmq6cxRQyXFHo8',
    thumb1: 'https://i.scdn.co/image/98eda32c4bd07da1c59e1bccd5f985aa426c020d',
    thumb2: 'https://i.scdn.co/image/90ca8dafc771892c850f5729290ed5c898a227a4',
    thumb3: 'https://i.scdn.co/image/f4e2344d9476c82591c8444b3305bee9f337ed23',
    description: 'SCENKONSTBIENNALEN 2019: HJÄLTE FÖR HUR LÄNGE? - OM INHOPP Arrangeras av: Stockholms Konstnärliga högskola Scensverige vimlar av ersättare. Men vad innebär det i praktiken att göra ett inhopp – för mig som skådespelare, för föreställningen och för publiken? I mitt, inom Stockholms konstnärliga högskola, pågående forskningsprojekt om inhopp, undersöker jag inhoppets förutsättningar och konsekvenser på, bakom och utanför scenerna. Jag vill passa på att både redovisa mina nuvarande tankar gällande inhoppets möjligheter och fällor och samtidigt diskutera med den närvarande publiken kring deras erfarenheter och tankar för att på så sätt vara i dialog med kollegor och andra berörda under den forskande processen. Medverkande: Niklas Hald, skådespelare, föreläsare INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED STOCKHOLMS KONSTNÄRLIGA HÖGSKOLA UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: HJÄLTE FÖR HUR LÄNGE?...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','hjälte','audio'],
    title: '#107 Hjälte för hur länge? – om inhopp på scenen med skådespelaren Niklas Hald (LIVE: 2019-05-16)',
    short_title: '#107 Hjälte för hur länge? 2019-05-16',
    collaborators: ['Stockholms Konstnärliga högskola','Scenkonstbiennalen'],
    cast: ['Niklas Hald'],
    date: '2019-06-03',
  },
  {
    id: 93,
    order: '8',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '1YUgPSaNXJQtttp7FoiOV1',
    thumb1: 'https://i.scdn.co/image/493f147ad9066c6617fd6965de4ff23a65b0980c',
    thumb2: 'https://i.scdn.co/image/79ef92ae7c403d3f828ae9e8e5a63f9c2fead822',
    thumb3: 'https://i.scdn.co/image/8b2abb6aac6fd950e424a55d4e295e858a05dd63',
    description: 'SCENKONSTBIENNALEN 2019: DRAMATIKER OCH REGISSÖRER – EN KÄRLEKSFULL BROTTNINGSMATCH? Arrangerat av: Sveriges Dramatikerförbund Hur jobbar vi med regissörerna? Tjänar texten på att få synpunkter och kommentarer under hela skrivprocessen, eller kan just kollisionen mellan dramatiker och regissör ta uppsättningen till högre höjder? Dramatikerna Johanna Emanuelsson och Dimen Abdulla diskuterar och utbyter erfarenheter om komplexiteten i samarbeten, som utvecklat dem eller gjort dem alltför kompromissvilliga. Hur ska man få till det perfekta samspelet? Medverkande: Johanna Emanuelsson, Dramatiker Dimen Abdulla, Dramatiker Moderator: Birgit Hageby INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED SVERIGES DRAMATIKERFÖRBUND UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: DRAMATIKER OCH REGISSÖRER...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','dramatiker','regissörer','audio'],
    title: '#108 Dramatiker & regissörer – en kärleksfull brottningsmatch? (LIVE: 2019-05-16)',
    short_title: '#108 Dramatiker & regissörer –',
    collaborators: ['Dramatikerförbund','Scenkonstbiennalen'],
    cast: ['Johanna Emanuelsson','Dimen Abdulla','Birgit Hageby'],
    date: '2019-06-03',
  },
  {
    id: 84,
    order: '9',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '4QMErwznEKoE3YAQdhQt8U',
    thumb1: 'https://i.scdn.co/image/4bfe82f81448263201e7b26591242fc3d3b6cda6',
    thumb2: 'https://i.scdn.co/image/443f7e63121fcf67f61c646e352dc69ffa0dc89c',
    thumb3: 'https://i.scdn.co/image/8067a62760a2a6190f86ed816a03085535bf95d6',
    description: 'SCENKONSTBIENNALEN 2019: SCENOGRAFI ÄR DET SOM FORTFARANDE INTE SYNS Arrangeras av: Ulla Kassius Jag vill tala om scenografi. Efter mer än fyrtio års arbete som scenograf, några regiarbeten och erfarenhet som lärare och föreläsare vill jag tala om både scenografen och scenografins roll på teatern. Utifrån några påståenden som ”scenografi är det som inte syns” och ”scenografi som bromskloss” skulle jag också vilja tala om scenografins betydelse för teaterns förnyelse och för dess stagnation. Några spaningar om vad som händer just nu på teaterscenerna, om förhållandet mellan regi, skådespeleri och scenografi. Ett samtal om scenografi, konst, politik och publik för och med skådespelare, regissörer, kostym- mask- ljud -och ljusdesigners. Föreläsare: Ulla Kassius, scenograf Bildspel till föreläsningen: https://www.dropbox.com/s/zpajqdq1eby8jel/PDF-Ulla%20Kassius.pdf?dl=0 Fotograf: Lia Jacobi / Scenkonst Västernorrland Ljudupptagning: Åsa Holtz INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED ULLA KASSIUS UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: SCENOGRAFI ÄR DET SOM FORTFARANDE INTE SYNS...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','scenografi','scenograf','audio'],
    title: '#109 Ulla Kassius – Scenografi är det som inte syns (LIVE: 2019-05-17)',
    short_title: '#109 Ulla Kassius – Scenografi är det som inte syns',
    collaborators: ['Ulla Kassius','Scenkonstbiennalen'],
    cast: ['Ulla Kassius','Lia Jacobi','Åsa Holtz'],
    date: '2019-06-04',
  },
  {
    id: 97,
    order: '10',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '0yOM2ii428xR4L5CsSrXM0',
    thumb1: 'https://i.scdn.co/image/cbbc1026dc62be10f177902c9466ab9aea727a2d',
    thumb2: 'https://i.scdn.co/image/63d85eeb052a4a042e46064de36d324e4c140a89',
    thumb3: 'https://i.scdn.co/image/e42eb4ba79c5ce750659dd7ebce975e78d3fe000',
    description: 'SCENKONSTBIENNALEN 2019: DO I REALLY NEED A DRAMATURG? - A BRIEF INTRODUCTION INTO WHAT DANCE DRAMATURGY ACTUALLY DOES Arrangerat av: Danscentrum Riks In the field of dance, dramaturgy is still a relatively new discipline and a new profession, which is therefore still viewed with curiosity and suspicion. All too often one wonders what dramaturgy actually is. But instead of losing ourselves in attempts at definition, I will concentrate more on what dramaturgy can actually do and achieve, both for choreographers and for dance as such. Thus, various dramaturgical practices and methods will be introduced and critically discussed with the audience, such as dramaturgy as a structural, collaborative, contextualizing practice, etc. Seminar leader: Thomas Schaupp, dramaturg Thomas Schaupp is a free-lancing dance dramaturg based in Berlin. He is collaborating with several international choreographers, currently with Anne-Mareike Hess, Janne-Camilla Lyster, Camille Mutel and Stian Danielsen. As a mentor and advisor for young choreographers he collaborates with institutions such as Dansearena Nord in Hammerfest and KHIO in Oslo. Thomas is a guest teacher at the Inter-University Centre for Dance in Berlin and facilitates workshops on dance-dramaturgy in choreographic centres across Europe. In collaboration with Ibsen International and Goethe Institut Beijing he also co-curates a Cultural Exchange Program on Dance Dramaturgy in China. PRODUCED FOR K-PLAY BY KULTURAKADEMIN IN COLLABORATION WITH DANSCENTRUM RIKS UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: DO I REALLY NEED A DRAMATURG?',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','dramaturg','audio'],
    title: '#110 Do i really need a dramaturg? – Introduction into dance dramaturgy (LIVE: 2019-05-17)',
    short_title: '#110 Do i really need a dramaturg?',
    collaborators: ['Danscentrum','Scenkonstbiennalen'],
    cast: ['Thomas Schaupp','Anne-Mareike Hess','Janne-Camilla Lyster','Camille Mutel','Stian Danielsen'],
    date: '2019-06-10',
  },
  {
    id: 76,
    order: '11',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '6Xtdv4ZRT3k1Eq8enoVkxH',
    thumb1: 'https://i.scdn.co/image/a145a3b85c9f615399cf14e42f1f744ff6560292',
    thumb2: 'https://i.scdn.co/image/c51382431044b51706835492bae670ba698fe933',
    thumb3: 'https://i.scdn.co/image/96f5dcaff997816cf38661bb3054b45becd45ebc',
    description: 'SCENKONSTBIENNALEN 2019: I BEGYNNELSEN VAR ORDET Arrangeras av: Sveriges Dramatikerförbund Ett seminarium, där de dramatiker, som står bakom tre av de utvalda produktionerna till Scenkonstbiennalen 2019: Glasäpplen, Hamlet, och Ocean redogör, mycket handfast, för sina arbetsmetoder och textens tillblivelse i de aktuella uppsättningarna. Dramaturgerna Birgit Hageby och Magnus Lindman ställer frågor och samtalar med manusförfattarna. Medverkande: Anders Duus, dramatiker Jens Ohlin och Hannes Meidal, dramatiker Paula Stenström Öhman, dramatiker Moderator: Birgit Hageby och Magnus Lindman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED SVERIGES DRAMATIKERFÖRBUND UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: I BEGYNNELSEN VAR ORDET...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','dramaturg','audio'],
    title: '#111 I begynnelsen var ordet – ett samtal mellan dramatiker (LIVE: 2019-05-17)',
    short_title: '#111 I begynnelsen var ordet – ett samtal mellan dramatiker',
    collaborators: ['Sveriges Dramatikerförbund','Scenkonstbiennalen'],
    cast: ['Anders Duus','Jens Ohlin','Hannes Meidal','Paula Stenström Öhman','Birgit Hageby','Magnus Lindman'],
    date: '2019-06-10',
  },
  {
    id: 92,
    order: '12',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '2F6HLP3sGTcthd7LrOq5Ue',
    thumb1: 'https://i.scdn.co/image/e4054c8bb52ba2bc284c1c6b9d8e2212cbece317',
    thumb2: 'https://i.scdn.co/image/efe6e0fa231df7bd4a098fd03acddffe038ef372',
    thumb3: 'https://i.scdn.co/image/b7bfc23ebd78c45658aa1d4a54a89d7460e43cec',
    description: 'SCENKONSTBIENNALEN 2019: SCENISKA MIRAKEL 2 - VAD ÄR DET DÄR FIGURTEATER FÖR NÅGOT? Arrangeras av: Unima – Sverige, Kulturakademin och FIGUR – nationellt figurteatercentrum Vad är figurteater? Vad skiljer respektive förenar figurteater och annan scenkonst? Hur är det att recensera denna scenkonstform? Figurteater som vänder sig till en vuxen publik, något som hittills var ovanligt i Sverige, hur är utvecklingen av den? Kring dessa frågor diskuterar regissören Erik Holmström, skådespelarna Malin Morgan och Malin Halland med teater och danskritikern Lis Hellström Sveningson och dockspelaren/dockmakaren Jenny Bjärkstedt. Vad har figurteatern betytt för dom i sina respektive arbeten? Hur började eller upptäckte dom denna scenkonstform? Medverkande: Erik Holmström, Regissör Jenny Bjärkstedt, dockskapare Malin Morgan, skådespelare Malin Halland, skådespelare och dockspelare Moderator: Lis Hellström Sveningson, kritiker INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED UNIMA – SVERIGE & FIGUR – NATIONELLT FIGURTEATERCENTRUM UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: SCENISKA MIRAKEL 2...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','figurteater','audio'],
    title: '#112 Sceniska mirakel 2 - vad är det där figurteater för något? (LIVE: 2019-05-17)',
    short_title: '#112 Sceniska mirakel 2 - vad är det där figurteater för något?...',
    collaborators: ['Unima – Sverige','Kulturakademin','FIGUR – nationellt figurteatercentrum','Scenkonstbiennalen'],
    cast: ['Erik Holmström','Jenny Bjärkstedt','Malin Morgan','Malin Halland','Lis Hellström Sveningson'],
    date: '2019-06-11',
  },
  {
    id: 87,
    order: '13',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '3z4kGwWc46ZsQqBI2lFNUF',
    thumb1: 'https://i.scdn.co/image/4a7dacb2a2c27f27bec499a41ffb4ab53ee7e9ca',
    thumb2: 'https://i.scdn.co/image/8154e54ac2780e0268c30b8c5d19443106debca6',
    thumb3: 'https://i.scdn.co/image/ebd2766f0d7a0edf520143480b69420b158782a9',
    description: 'SCENKONSTBIENNALEN 2019: ATT GESTALTA SOCIALT UTANFÖRSKAP UTAN SOCIAL REALISM Arrangeras av: Riksteatern Hur hitta vi konstnärliga vägar att gestalta ämnen eller situationer som tar avstamp i sociala dilemman? kan vi lita på konsten? Måste inte uppsättningar vara tydliga och i princip lärostycken. Vilka vinster finns att belysa ett ämne ur ett oväntat håll. Vad är i så fall ett oväntat håll? Var kan en gå vilse i detta arbete? Kan publiken utsättas för konstnärligt osäkrade rum. Går det att tvinga in flera ”discipliner” / ”formspråk” som kan öppna upp för nya tankar? Talar konsten sanning? Medverkande: Martin Rosengardten, Regissör och Skådespelare Helle Rossing, Regissör, studerande på STDH Isak Hjelmskog, Regissör och Skådespelare Moderator: Bengt Andersson, Konstnärlig ledare Barn & Unga Riksteatern INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED RIKSTEATERN UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: ATT GESTALTA SOCIALT UTANFÖRSKAP UTAN SOCIAL REALISM...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','realism','audio'],
    title: '#113 Att gestalta socialt utanförskap utan social realism (LIVE: 2019-05-17)',
    short_title: '#113 Att gestalta socialt utanförskap utan social realism',
    collaborators: ['Riksteatern','Scenkonstbiennalen'],
    cast: ['Martin Rosengardten','Helle Rossing','Isak Hjelmskog','Bengt Andersson'],
    date: '2019-06-12',
  },
  {
    id: 77,
    order: '14',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '6uTHE9aeeD9mlhH8hRUKPH',
    thumb1: 'https://i.scdn.co/image/3fd56014bf6b2dfe274296abcbd0f52e9c5f9051',
    thumb2: 'https://i.scdn.co/image/62935a7530e17af1574446d4dc253ce8f7b2425f',
    thumb3: 'https://i.scdn.co/image/6f3ac51e66d90009f4c55cefe1af6af4c1c5d3ff',
    description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN - SÅ FUNKAR DET! Arrangeras av: Bohm Bohm Room Hur uppstår nya och interdisciplinära samarbeten inom scenkonsten i praktiken? I det här samtalet vill vi lyfta fram några aktuella exempel, tillvägagångssätt och erfarenheter från tre ledare och organisationer som på olika sätt skapat möten mellan olika uttryck och kompetenser. Hur påverkar gränsöverskridande samarbeten formen för presentation, publikmöten och den kreativa processen? Vad finns det några skillnader och möjligheter beroende på om verksamheten arbetar lokalt, nationellt eller internationellt? Medverkande: Helena Seth, Programansvarig för Dramaten Moderator: Emelie Bergbohm, VD, Bohm Bohm Room INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED BOHM BOHM ROOM UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#114 Helena Seth (Dramaten) - Gränsöverskridande samarbeten (LIVE: 2019-05-17)',
    short_title: '#114 Helena Seth (Dramaten) - Gränsöverskridande samarbeten',
    collaborators: ['Bohm Bohm Room','Scenkonstbiennalen'],
    cast: ['Helena Seth','Emelie Bergbohm'],
    date: '2019-06-12',
  },
  {
    id: 94,
    order: '15',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '1nf381B2BzuKZfEd3Yt5Tm',
    thumb1: 'https://i.scdn.co/image/e6974c77c7b7c4c3c3464f685311449ae3af32b6',
    thumb2: 'https://i.scdn.co/image/f7b4774430c40e663b0dd17bce760ee054f8cfc7',
    thumb3: 'https://i.scdn.co/image/2061cb3b24c4f2a79b61245cacf7b20e51ecfa18',
    description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN - SÅ FUNKAR DET! Arrangeras av: Bohm Bohm Room Hur uppstår nya och interdisciplinära samarbeten inom scenkonsten i praktiken? I det här samtalet vill vi lyfta fram några aktuella exempel, tillvägagångssätt och erfarenheter från tre ledare och organisationer som på olika sätt skapat möten mellan olika uttryck och kompetenser. Hur påverkar gränsöverskridande samarbeten formen för presentation, publikmöten och den kreativa processen? Vad finns det några skillnader och möjligheter beroende på om verksamheten arbetar lokalt, nationellt eller internationellt? Medverkande: Staffan Becker, VD Vara konserthus Moderator: Emelie Bergbohm, VD, Bohm Bohm Room INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED BOHM BOHM ROOM UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#115 Staffan Becker (Vara konserthus) - Gränsöverskridande samarbeten (LIVE: 2019-05-17)',
    short_title: '#115 Staffan Becker (Vara konserthus)',
    collaborators: ['Bohm Bohm Room','Scenkonstbiennalen'],
    cast: ['Staffan Becker','Emelie Bergbohm'],
    date: '2019-06-12',
  },
  {
    id: 91,
    order: '16',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '2LLP4zdted7zNF4tRNYxo9',
    thumb1: 'https://i.scdn.co/image/24b414b178c6ff3dca2bb0512ca281fac7b8ae6b',
    thumb2: 'https://i.scdn.co/image/c9b7b4199b9c297d9fb9eb81ddd26206fdd1549a',
    thumb3: 'https://i.scdn.co/image/a69f707a0dcd789cbe8269024e57e69be71595e6',
    description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN - SÅ FUNKAR DET! Arrangeras av: Bohm Bohm Room Hur uppstår nya och interdisciplinära samarbeten inom scenkonsten i praktiken? I det här samtalet vill vi lyfta fram några aktuella exempel, tillvägagångssätt och erfarenheter från tre ledare och organisationer som på olika sätt skapat möten mellan olika uttryck och kompetenser. Hur påverkar gränsöverskridande samarbeten formen för presentation, publikmöten och den kreativa processen? Vad finns det några skillnader och möjligheter beroende på om verksamheten arbetar lokalt, nationellt eller internationellt? Medverkande: Mira Helenius Martinsson, tillträdande VD och konstnärlig ledare för Skånes Dansteater, tidigare Norrdans och Västernorrlands danschef Moderator: Emelie Bergbohm, VD, Bohm Bohm Room INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED BOHM BOHM ROOM UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#116 Mira Helenius Martinsson (Skånes Dansteater) - Gränsöverskridande samarbeten (LIVE: 2019-05-17)',
    short_title: '#116 Mira Helenius Martinsson (Skånes Dansteater)',
    collaborators: ['Bohm Bohm Room','Scenkonstbiennalen'],
    cast: ['Mira Helenius Martinsson','Emelie Bergbohm'],
    date: '2019-06-12',
  },
  {
    id: 64,
    order: '17',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '629MA3HBG9MaO4tqdWpTjP',
    thumb1: 'https://i.scdn.co/image/11ddfd9989a8681226b04196e7be892faab74e6b',
    thumb2: 'https://i.scdn.co/image/73a1d3c8287d993a2482ca7a8dd03a319120d61b',
    thumb3: 'https://i.scdn.co/image/20bdd14406e53501e00928811f23511a2b2275b6',
    description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN - SÅ FUNKAR DET! Arrangeras av: Bohm Bohm Room Hur uppstår nya och interdisciplinära samarbeten inom scenkonsten i praktiken? I det här samtalet vill vi lyfta fram några aktuella exempel, tillvägagångssätt och erfarenheter från tre ledare och organisationer som på olika sätt skapat möten mellan olika uttryck och kompetenser. Hur påverkar gränsöverskridande samarbeten formen för presentation, publikmöten och den kreativa processen? Vad finns det några skillnader och möjligheter beroende på om verksamheten arbetar lokalt, nationellt eller internationellt? Medverkande: Staffan Becker, VD Vara konserthus Helena Seth, Programansvarig för Dramaten Mira Helenius Martinsson, tillträdande VD och konstnärlig ledare för Skånes Dansteater, tidigare Norrdans och Västernorrlands danschef Moderator: Emelie Bergbohm, VD, Bohm Bohm Room INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED BOHM BOHM ROOM UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: GRÄNSÖVERSKRIDANDE SAMARBETEN I PRAKTIKEN...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#117 Panelsamtal - Gränsöverskridande samarbeten i praktiken – så funkar det! (LIVE: 2019-05-17)',
    short_title: '#117 Panelsamtal - Gränsöverskridande samarbeten i praktiken',
    collaborators: ['Bohm Bohm Room','Scenkonstbiennalen'],
    cast: ['Staffan Becker','Helena Seth','Mira Helenius Martinsson','Emelie Bergbohm'],
    date: '2019-06-12',
  },
  {
    id: 88,
    order: '18',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '3RGyruvjQax10zV83K6zBa',
    thumb1: 'https://i.scdn.co/image/864e5e9cebace56cd7cc1747f21fa9f6ed492cae',
    thumb2: 'https://i.scdn.co/image/c4ea5e82eca4c9318df04e4b3ee2053da379b5c9',
    thumb3: 'https://i.scdn.co/image/dce021155e332aa1f3f98ef6a4fe397d57c67d73',
    description: 'SCENKONSTBIENNALEN 2019: INFORMATIONSTRÄFF - KONSTNÄRSNÄMNDEN INFORMERAR OM SINA STIPENDIER OCH BIDRAG Arrangeras av: Konstnärsnämnden Konstnärsnämnden är en statlig myndighet som fördelar stipendier och bidrag till yrkesverksamma konstnärer inom bild, form, musik, dans, teater och film. Stöden riktar sig till frilansande konstnärer bosatta i Sverige och/eller har sin huvudsakliga konstnärliga med verksamhet i Sverige. Inom scenkonst kan stöd ges för internationella resor och utbyten, projekt, konstnärlig utveckling samt residens. Vi berättar om våra stödformer och vad du ska tänka på när du söker. Efteråt kan du få personlig rådgivning av våra handläggare. Medverkande: Tina Pettersson (handläggare teater) Anneli Strömqvist (handläggare dans), Ophélie Alegre (handläggare scenkonst med fokus dans) INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KONSTNÄRSNÄMNDEN UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: INFORMATIONSTRÄFF',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#118 Konstnärsnämnden – information om stipendier och bidrag (LIVE: 2019-05-17)',
    short_title: '#118 Konstnärsnämnden – information om stipendier och bidrag',
    collaborators: ['Konstnärsnämnden','Scenkonstbiennalen'],
    cast: ['Tina Pettersson','Anneli Strömqvist','Ophélie Alegre'],
    date: '2019-06-18',
  },
  {
    id: 68,
    order: '19',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '39nBoKerVjTcK0Ek3LvyOM',
    thumb1: 'https://i.scdn.co/image/c23abc1db853b96dcac0d532d041c8e494276034',
    thumb2: 'https://i.scdn.co/image/7ea62016791868fba1ac04514f089e3a9a8c5569',
    thumb3: 'https://i.scdn.co/image/c704aea175d0a89565662b6650bd1021233a9942',
    description: 'SCENKONSTBIENNALEN 2019: NÄR VI TRÄFFADE VARANN - OCH GJORDE EN PJÄS IHOP Arrangeras av: Riksteatern Delaktighetsprocesser skapar alltid nya relationer. I arbetet med Riksteaterns “När vi träffade varann” involverades erfarenhetsbärare, publik och arrangörer tidigt och genom hela processen. Vilka blev utmaningarna och förtjänsterna? Hur kan ett deltagande arbete i turnerande kontext struktureras? Vilka särskilda förutsättningar krävs av medarbetare och organisation? Möt medlemmar från produktionsteam och arrangörer i ett gemensamt samtal om vägen från idé, genom skrivande och iscensättning till turné. Ett seminarium om att (ovanligt) många gör en produktion ihop. Medverkande: Ninna Tersman (dramatiker) Mahmoud Al Zeeb (konstnärligt råd/arrangör Kopparberg) Gunilla Larsson (skådespelare) Joakim Rindå (dramatiker/regissör) Maria Björkman (producent) Linnea Byberg (arrangör Boden) INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED RIKSTEATERN UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: NÄR VI TRÄFFADE VARANN',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#119 När vi träffade varann – och gjorde en pjäs ihop (LIVE: 2019-05-17)',
    short_title: '#119 När vi träffade varann',
    collaborators: ['Riksteatern','Scenkonstbiennalen','scenteknik'],
    cast: ['Ninna Tersman','Mahmoud Al Zeeb','Gunilla Larsson','Joakim Rindå','Maria Björkman','Linnea Byberg'],
    date: '2019-06-18',
  },
  {
    id: 80,
    order: '20',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '5TKbWC4iKm3iq4AUaQ234P',
    thumb1: 'https://i.scdn.co/image/1b9dddbf6a29bd4d323121decc12381f328c09c6',
    thumb2: 'https://i.scdn.co/image/7d1688c0c72c30fb6e09f496d7da94ac710f1027',
    thumb3: 'https://i.scdn.co/image/c703c5cd1c5e1df0e2b13a7c440f8af80bae6bb5',
    description: 'SCENKONSTBIENNALEN 2019: FLERSPRÅKIG SCENKONST: KONSTNÄRLIGA MÖJLIGHETER OCH UTMANINGAR Arrangeras av: Stockholms Dramatiska Högskola, Institutionen för Scenkonst i samarbete med Unga Klara och Kulturhuset Stadsteatern I ett samhälle och en värld där olika krafter strävar efter språklig och etnisk homogenitet kan scenkonsten aktivt arbeta för språklig och kulturell mångfald. En stor del av befolkningen och den potentiella publiken i Sverige är flerspråkig, hur förhåller sig scenkonstbranschen till det och hur inkluderas denna erfarenhet inom scenkonsten? Seminariet undersöker i dialog med panel och publik vilka konstnärliga möjligheter/fördelar och utmaningar/svårigheter flerspråkig scenkonst kan innebära. Medverkande: Nina Rashid, skådespelare (Unga Klara) Åsa Simma (Hoavda/Teaterchef Giron Sámi Teáhter) Vanja Hamidi Isacson (Dramatiker & doktorand Stockholms dramatiska högskola) Maria Rydell (Lektor i nordiska språk på institutionen för svenska & flerspråkighet Stockholms universitet) Moderator: Åsa Johannisson INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED STOCKHOLMS DRAMATISKA HÖGSKOLA, INSTITUTIONEN FÖR SCENKONST I SAMARBETE MED UNGA KLARA OCH KULTURHUSET STADSTEATERN UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: FLERSPRÅKIG SCENKONST...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','flerspråkig','audio'],
    title: '#120 Flerspråkig scenkonst – Konstnärliga möjligheter och utmaningar (LIVE: 2019-05-18)',
    short_title: '#120 Flerspråkig scenkonst:',
    collaborators: ['Stockholms Dramatiska Högskola','Institutionen för Scenkonst - Unga Klara','Kulturhuset Stadsteatern','Scenkonstbiennalen'],
    cast: ['Nina Rashid','Åsa Simma','Vanja Hamidi Isacson','Maria Rydell'],
    date: '2019-06-18',
  },
  {
    id: 83,
    order: '21',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '4ZS10h9yEWVHV6i5CYv40e',
    thumb1: 'https://i.scdn.co/image/b706fbe271299ae9998bcc0b121880d1e3ee84bf',
    thumb2: 'https://i.scdn.co/image/8c3522fda30af4abf91bbd95ee8c8de6af566755',
    thumb3: 'https://i.scdn.co/image/597e867caef6353e068ec7dc0aed44bdf069770c',
    description: 'SCENKONSTBIENNALEN 2019: FRÅN SCEN TILL SKÄRM – VAD HÄNDER EMELLAN? Arrangör: Orionteatern Från scen till skärm – vad händer emellan? Ett samtal om de konstnärliga valen i överföring från scenkonst till filmmediet. Hur fångar man essensen i en scenkonstföreställning? Och hur mycket har man att säga till om som regissör till en föreställning som ska filmatiseras? Behöver vi tänka om i dramatiseringen? Möt filmaren Fredrik Egerstrand som överfört föreställningen Det flygande barnet i regi av Lars Rudolfsson till tv. Och Jens Ohlin, författare (tillsammans med Hannes Meidal) och regissör till Hamlet (Teater Galeasen) som visas på Biennalen i filmversion. Medverkande: Fredrik Egerstrand, filmregissör Jens Ohlin, regissör Moderator: Gita Mallik, Orionteatern INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED ORIONTEATERN UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: FRÅN SCEN TILL SKÄRM VAD HÄNDER EMELLAN?',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#121 Från scen till skärm – i överföring från scenkonst till filmmediet (LIVE: 2019-05-18)',
    short_title: '#121 Från scen till skärm –',
    collaborators: ['Orionteatern','Scenkonstbiennalen'],
    cast: ['Fredrik Egerstrand','Jens Ohlin','Gita Mallik'],
    date: '2019-06-18',
  },
  {
    id: 67,
    order: '22',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '71bHLgcRhBDGAf7YWG95Bs',
    thumb1: 'https://i.scdn.co/image/1cd5f393be15e8c52ee257f302132081fd85bcac',
    thumb2: 'https://i.scdn.co/image/571b2a5f467d6290313bae3bd242698a2e06882b',
    thumb3: 'https://i.scdn.co/image/6b1fa4deae28b6474974e03c1f84da80bbb5ee13',
    description: 'SCENKONSTBIENNALEN 2019: DANSLYFTET - INBJUDAN TILL SAMTAL OM DEN FRIA DANSSEKTORN Arrangeras av: Danscentrum Riks Danscentrum har i en kulturpolitisk arbetsgrupp sammanställt den fria danssektorns utmaningar. Hur går det till att vara yrkesverksam, skapa och presentera dans? Vilka är behoven och var finns lösningarna för publiken, danskonstens utveckling, koreografen, dansaren, arrangören och producenten, lokalt, regional och nationellt. I ett samtal med publiken presenterar arbetsgruppen sina slutsatser och utkast till handlingsplan. Hur tar vi arbetet vidare? Medverkande: Marie Wårell (Norr) Emelie Johansson (Sthlm) Pia Nordin (Väst) Maria Naidu (Syd) Maria Rydén (ordförande Riks) Amy Fee (Riks) INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED DANSCENTRUM RIKS UNDER SCENKONSTBIENNALEN 2019.',
    short_description: 'SCENKONSTBIENNALEN 2019: DANSLYFTET INBJUDAN TILL SAMTAL OM DEN FRIA DANSSEKTORN...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#122 Danslyftet – samtal om den fria danssektorn (LIVE: 2019-05-18)',
    short_title: '#122 Danslyftet – samtal om den fria danssektorn',
    collaborators: ['Danscentrum Riks','Scenkonstbiennalen'],
    cast: ['Marie Wårell','Emelie Johansson','Pia Nordin','Maria Naidu','Maria Rydén','Amy Fee'],
    date: '2019-06-18',
  },
  {
    id: 89,
    order: '23',
    type: 'audio',
    playlists: ['scenkonstbiennalen','scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '2yKSHr8azp0AIRZIsunmHm',
    thumb1: 'https://i.scdn.co/image/8a04729b27876df8113358bcc9a69967d0a6f413',
    thumb2: 'https://i.scdn.co/image/e9dbae46301431d748f035e0c0336e61ce67d2d9',
    thumb3: 'https://i.scdn.co/image/9aff5b3c9270ba6e90cdf524c7786513ddb0283c',
    description: 'SCENKONSTBIENNALEN 2019: NORDIC STAGE – NORDISK DRAMATIK I USA Organizer: Bergman Studio, Royal Dramatic Theatre and Swedish Embasy, Washington DC How can new Swedish and Nordic theatre reach an international audience? In a unique collaboration between the collective text development project Bergman Studio from Sweden´s Royal Dramatic Theatre and the Scandinavian American Theater Company (SATC) some ten new Swedish plays have met new audiences through staged readings in New York and Washington DC. Participants: Jacob Hirdwall, Head Bergman Studio Linda Zachrison, Counsellor for Cultural Affairs, Swedish Embassy in Washington DC Hilkka-Liisa Livanainen and Albert Bendix, Scandinavia American Theater Company (SATC) Tanja Lorentzon, Playwright and Actor PRODUCED FOR K-PLAY BY KULTURAKADEMIN IN COLLABORATION WITH BERGMAN STUDIO, ROYAL DRAMATIC THEATRE AND SWEDISH EMBASY, WASHINGTON DC UNDER SCENKONSTBIENNALEN 2019',
    short_description: 'SCENKONSTBIENNALEN 2019: NORDIC STAGE – NORDISK DRAMATIK I USA...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','scenkonstbiennalen','audio'],
    title: '#123 Nordic Stage – Nordisk Dramatik i USA (LIVE: 2019-05-18)',
    short_title: '#123 Nordic Stage – Nordisk Dramatik i USA',
    collaborators: ['Bergman Studio','Royal Dramatic Theatre','Swedish Embasy - Washington DC','Scenkonstbiennalen'],
    cast: ['Jacob Hirdwall','Linda Zachrison','Hilkka-Liisa Livanainen','Albert Bendix','Tanja Lorentzon'],
    date: '2019-06-18',
  },
  {
    id: 74,
    order: '1',
    type: 'audio',
    playlists: ['scenteknik'],
    categories: ['allt','scenteknik','scenkonst'],
    level: 'Masterclass',
    media_id: '7EkQ3BqzbA2T24f164te2Z',
    thumb1: 'https://i.scdn.co/image/801717bcbdcbbd90fd1f0f16faf2425660efc608',
    thumb2: 'https://i.scdn.co/image/02c255ab9416095bf3565516a0c41656e0ce6ea3',
    thumb3: 'https://i.scdn.co/image/8dcb86163adb17309ebb5d31de3c4d8fd3269a0e',
    description: 'FADING LIGHTS - THE TRANSITION FROM CANDLE TO LED With Chris Van Goethem Powerpoint: https://www.dropbox.com/s/hsb8ba6etjozedu/Fading%20lights%20Kulturakademin%20v1_51.pdf?dl=0 Organizer: Kulturakademin in collaburation with YRGO, Folkteatern & Svensk Teaterteknisk Förening ”Lighting has always been an important part of theatre performance and changes in light sources have influenced the way performance, costume, sets and staging have developed. The joint research project of RITCS - School of Arts, Brussels and SADA - Stockholm, focusses on these changes and how practitioners dealt with them. The practice based approach, research by doing, is derived from the day to day research that is done in every theatre company when developing new techniques or effects. The goal is to develop useful insights for the contemporary practice. In this lecture we give an overview of the most important changes in lighting technology and the way they were implemented in theatre practice. The focus on the change processes and the issues and failures that came with them will throw a different light on contemporary and future challenges in changing technology. It will show the importance of understanding our heritage and history for the new innovative practice. Fundamentally, the history of lighting is about taking control over light as a physical phenomenon. It is the path from “turning on the light” towards “designing light”. It is about making magic with an untouchable element.” Chris Van Goethem Lecturer: Chris Van Goethem teaches at the stage management and technical theatre department of RITCS (EHB), Sabbattini Antwerp en Marotech Oujda (Marokko). He is a guest lecturer at Pianofabriek, Arteveldehogeschool, SFP, Accademia Teatro alla Scala, YRGO (Goteborg) and Frans Schartaus Handelsinstitut/Business Institute in Stockholm. He teaches History of Technical Theatre, Research skills, production management and Special Effects. He is responsible for the expertise centre for technical theatre of RITS, school of arts, Erasmus University College Brussels and is involved in research on education, competence management, history and technical theatre. (https://www.podiumtechnieken.be/en ) He researches the history of technical theatre and was part of the “Changement a vue” research project. At the moment he is part of the Fading lights project. Both projects are conducted in cooperation with SADA, Uniarts, Stockholm. Chris Van Goethem is member of the board of STEPP, the Belgian professional organization of technicians. PRODUCED FOR K-PLAY BY KULTURAKADEMIN IN COLLABORATION WITH YRGO, FOLKTEATERN & SVENSK TEATERTEKNISK FÖRENING.',
    short_description: 'FADING LIGHTS - THE TRANSITION FROM CANDLE TO LED...',
    tags: ['podcast','learning','k-play','scenteknik','scenkonst','fading lights','fading','lights','audio'],
    title: '#124 Fading Lights - The Transition From Candle To Led with Chris Van Goethem (LIVE: 2019-05-06)',
    short_title: '#124 Fading Lights - The Transition From Candle To Led',
    collaborators: ['YRGO','Folkteatern','Svensk Teaterteknisk Förening'],
    cast: ['Chris Van Goethem','Sabbattini Antwerp en Marotech Oujda (Marokko)','Frans Schartaus'],
    date: '2019-06-19',
  },
  {
    id: 72,
    order: '1',
    type: 'audio',
    playlists: ['film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '7in8bN702FbrG3ktXUdbIW',
    thumb1: 'https://i.scdn.co/image/6625ee595c43472346a2d49adbfdf2eca3e7280d',
    thumb2: 'https://i.scdn.co/image/71793765016c4d80a0a4babcba21c8219551da03',
    thumb3: 'https://i.scdn.co/image/c55e83563a878b7a1f045815099af928750dc6f5',
    description: 'SFI OCH FILM I VÄST: TVÅ FILMJÄTTAR I EN SMÄLL! Arrangeras av: Wift Väst, Film i Väst, Kulturakademin Panelsamtal om filmfinansieringens möjligheter och utmaningar. Lyssna på landets viktigaste aktörer i filmfinansieringen, arrangerad av WIFT Västra i samarbete med Film i Väst och Kulturakademin. Madeleine Ekman från Filminstitutet i Stockholm samtalar med Film i Västs Peter Possne, produktionschef, och Jenny Luukkonen, ansvarig för kort- och dokumentärfilm samt talangutveckling. Tillsammans ska de berätta om vad det är som gäller för filmfinansiering och ge svar till alla frågor som kan tänkas: Vilka berättelser fungerar bäst? Vad är det som bör undvikas? Vad prioriteras? Hur står det till med jämlikheten, vilka möjligheter och utmaningar finns? Medverkande: Madeleine Ekman, är långfilmskonsulent på Svenska filminstitutet. Peter Possne, är produktionschef på Film i Väst. Jenny Luukkonen, är ansvarig för kort- och dokumentärfilm samt talangutveckling på Film i Väst. Moderator: Monica Mazzitelli, är en italiensk regissör och författare. Hon är ansvarig för Wift Väst. INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED WIFT VÄST OCH FILM I VÄST',
    short_description: 'Example Short description...',
    tags: ['podcast','learning','k-play','film&tv','film','tv','sfi','audio'],
    title: '#126 SFI & Film i Väst – filmfinansieringens möjligheter & utmaningar',
    short_title: '#126 SFI & Film i Väst',
    collaborators: ['Wift Väst','Film i Väst','Kulturakademin'],
    cast: ['Madeleine Ekman','Peter Possne','Jenny Luukkonen','Monica Mazzitelli'],
    date: '2019-06-25',
  },
  {
    id: 78,
    order: '1',
    type: 'audio',
    playlists: ['musik'],
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: '6PsvmpvtKKVKrcYQiDtbpa',
    thumb1: 'https://i.scdn.co/image/dffe2131ec7d749df3799eebd833471386b39f29',
    thumb2: 'https://i.scdn.co/image/09a401858d35853441202c3bbc524b20738fe8ae',
    thumb3: 'https://i.scdn.co/image/7e76ea6a46c9c134a0948644c653dd0ff55bb267',
    description: 'Datum: 2019-05-29 Plats: Musikens Hus, Göteborg Senaste NYTT kring stöd och utbudskataloger för kultur för barn och unga. Arrangeras av: Kulturförvaltningen, Kultur i Väst, Musikcentrum Väst, Danscentrum Väst, Teatercentrum Väst Talare: Ida Kaivola - Kulturförvaltningen INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KULTUR I VÄST, KULTURFÖRVALTNINGEN, MUSIKCENTRUM VÄST, DANSCENTRUM VÄST, TEATERCENTRUM VÄST',
    short_description: 'Senaste NYTT kring stöd och utbudskataloger för kultur för barn och unga...',
    tags: ['podcast','learning','k-play','musik','audio','utbudskatalog'],
    title: '#127 Ida Kaivola - Kulturstöd och regler för utjämningsbidraget i Göteborg',
    short_title: '#127 Ida Kaivola - Kulturstöd och Regler',
    collaborators: ['Kulturförvaltningen','Kultur i Väst','Musikcentrum Väst','Danscentrum Väst','Teatercentrum Väst'],
    cast: ['Ida Kaivola'],
    date: '2019-06-26',
  },
  {
    id: 82,
    order: '1',
    type: 'audio',
    playlists: ['musik'],
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: '5L7lIySPSgixaRZigxnMLB',
    thumb1: 'https://i.scdn.co/image/cbf23cb7dcdfddc8b2574bfd29f4bc670cb6a65f',
    thumb2: 'https://i.scdn.co/image/3d4d9a233514302ceb18faefddfa8d4fc7b9bb3b',
    thumb3: 'https://i.scdn.co/image/7d9f757a1250b6e793ddd93779d7c1f6065d464f',
    description: 'Datum: 2019-05-29 Plats: Musikens Hus, Göteborg Senaste NYTT kring stöd och utbudskataloger för kultur för barn och unga. Arrangeras av: Kulturförvaltningen, Kultur i Väst, Musikcentrum Väst, Danscentrum Väst, Teatercentrum Väst Talare: Åsa Jansson, Konsulent barn och unga på Kultur i Väst INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KULTUR I VÄST, KULTURFÖRVALTNINGEN, MUSIKCENTRUM VÄST, DANSCENTRUM VÄST, TEATERCENTRUM VÄST',
    short_description: 'Senaste NYTT kring stöd och utbudskataloger för kultur för barn och unga...',
    tags: ['podcast','learning','k-play','musik','audio','utbudskatalog'],
    title: '#128 Åsa Jansson – Regionala arrangörsstödet för barn & unga - kulturkatalogen väst',
    short_title: '#128 Åsa Jansson – Regionala arrangörsstödet för barn & unga',
    collaborators: ['Kulturförvaltningen','Kultur i Väst','Musikcentrum Väst','Danscentrum Väst','Teatercentrum Väst'],
    cast: ['Åsa Jansson'],
    date: '2019-06-26',
  },
  {
    id: 73,
    order: '1',
    type: 'audio',
    playlists: ['musik'],
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: '7G2Dbe6hqH3nPq7hxugmOd',
    thumb1: 'https://i.scdn.co/image/8cc5cd7bf025a41e0b9409429981dbfbc74d63aa',
    thumb2: 'https://i.scdn.co/image/f70fb7e19b90472dce44988cf026ef0cb840f2dc',
    thumb3: 'https://i.scdn.co/image/30f385656637781997d619cb8b9bd13dd9cdba99',
    description: 'Datum: 2019-05-29 Plats: Musikens Hus, Göteborg Senaste NYTT kring stöd och utbudskataloger för kultur för barn och unga Arrangeras av: Kulturförvaltningen, Kultur i Väst, Musikcentrum Väst, Danscentrum Väst, Teatercentrum Väst Talare: Eeva Bolin, från Grundskoleförvaltningen och Förskoleförvaltningen INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KULTUR I VÄST, KULTURFÖRVALTNINGEN, MUSIKCENTRUM VÄST, DANSCENTRUM VÄST, TEATERCENTRUM VÄST',
    short_description: 'Senaste NYTT kring stöd och utbudskataloger för kultur för barn och unga...',
    tags: ['podcast','learning','k-play','musik','audio','utbudskatalog'],
    title: '#129 Eeva Bolin - Ny organisation för kultur i grundskola och förskola',
    short_title: '#129 Eeva Bolin -',
    collaborators: ['Kulturförvaltningen','Kultur i Väst','Musikcentrum Väst','Danscentrum Väst','Teatercentrum Väst'],
    cast: ['Eeva Bolin'],
    date: '2019-06-26',
  },
  {
    id: 95,
    order: '1',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '1N8IVXOy0qn61d6syYXh06',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM...',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#130 Adaptionsseminarium – ANIARA från bok till film med Pella Kågerman och Hugo Lilja',
    short_title: '#130 Adaptionsseminarium: ANIARA från bok till film',
    collaborators: ['Kreativa Europa Desk Sverige','Filmhuset'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Alexia Wennberg'],
    date: '2019-09-19',
  },
  {
    id: 85,
    order: '2',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '4l3txEd0VeR8U4QWA5DS6y',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM...',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#131 Adaptionsseminarium – CIRKELN från bok till film med Sara Bergmark Elfgren',
    short_title: '#131 Adaptionsseminarium – CIRKELN från bok till film',
    collaborators: ['Kreativa Europa Desk Sverige','Filmhuset'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Jan Göransson'],
    date: '2019-09-19',
  },
  {
    id: 86,
    order: '3',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '4BesUA60hGRxrS32PcLfSB',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#132 Adaptionsseminarium – ALEXIA WENNEBERG om litterära rättigheter, option och format',
    short_title: '#132 Adaptionsseminarium – ALEXIA WENNEBERG',
    collaborators: ['Kreativa Europa Desk Sverige','Filmhuset'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Alexia Wennberg','Jan Göransson'],
    date: '2019-09-19',
  },
  {
    id: 99,
    order: '4',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '0mfLQti6ZXwlj6aMzLi2jt',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM...',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#133 Adaptionsseminarium – Jämställdhet, litterära förlagor till film, tv och dataspel',
    short_title: '#133 Adaptionsseminarium – Jämställdhet',
    collaborators: ['Kreativa Europa Desk Sverige'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Alexia Wennberg','Jan Göransson'],
    date: '2019-09-19',
  },
  {
    id: 100,
    order: '5',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '00QVuu9hvUbAlTJ6esCFPT',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM...',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#134 Adaptionsseminarium – Trendspaning – epok, Svensk historia, genrer, finansiering',
    short_title: '#134 Adaptionsseminarium – Trendspaning',
    collaborators: ['Kreativa Europa Desk Sverige'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Jan Göransson'],
    date: '2019-09-19',
  },
  {
    id: 98,
    order: '6',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '0TNp6vSDIL5hiDo4ugDQWk',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM...',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#135 Adaptionsseminarium – Crowdfunding, Kick starter – faktorer som underlättar adaptionen',
    short_title: '#135 Adaptionsseminarium – Crowdfunding',
    collaborators: ['Kreativa Europa Desk Sverige'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Alexia Wennberg','Jan Göransson'],
    date: '2019-09-19',
  },
  {
    id: 66,
    order: '7',
    type: 'audio',
    playlists: ['adaptionsseminarium','film&tv'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '76MamtQazBh4W1erX7P3rH',
    thumb1: 'https://i.scdn.co/image/bb506ecc6dcad2fa41a87aab3b88364b7ec75dc0',
    thumb2: 'https://i.scdn.co/image/9450557588d5ee28690a30129ffbeaea64d3c063',
    thumb3: 'https://i.scdn.co/image/ecdc7386b3f185ad942bbbe5e7810e9407c2861b',
    description: 'Arrangeras av: Kreativa Europa Desk Sverige HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM. Det är alltid speciellt att se en filmatisering av en bok. Vilka val har gjorts i filmen och varför? Lyckas det skrivna ordet förmedlas till den vita duken? Statistiken visar att adaptioner oftast går bättre kommersiellt än originalhistorier, men vilka stora utmaningar finns i arbetet, och hur gör en egentligen för att lyckas skriva ett riktigt bra manus? Vi fördjupar oss i aktuella trender och framtiden, både nationellt och internationellt. Medverkande: Pella Kågerman och Hugo Lilja – manusförfattare och regissörer till filmen Aniara (nyligen nominerad som Sveriges Oscarsbidrag) baserad på Harry Martinsons stora rymdepos med samma namn. Sara Bergmark Elfgren – författare till boken Cirkeln som filmatiserats. Sara har dessutom skrivit för en mängd olika format. Alexia Wennberg – Producent på YellowBird där hon leder utvecklingen av nya filmer och serier. Nästa år ska hon producera sin första tv-serie – en adaption. 2013 började hon jobba som agent och startade och ledde avdelningen för manusförfattare på Salomonsson Agency. Moderator: Jan Göransson, Filminstitutets presschef Inspelningstekniker: Jan Cruseman INSPELAT FÖR K-PLAY AV KULTURAKADEMIN I SAMARBETE MED KREATIVA EUROPA DESK SVERIGE DEN 11 SEPTEMBER 2019 PÅ BIOGRAF MAURITZ, FILMHUSET, STOCKHOLM',
    short_description: 'HUR BRANSCHEN JOBBAR MED ADAPTION FRÅN BOK TILL FILM...',
    tags: ['podcast','learning','k-play','adaptionsseminarium','film&tv','audio'],
    title: '#136 Adaptionsseminarium – verktyg i arbetet med adaptionsprocessen',
    short_title: '#136 Adaptionsseminarium',
    collaborators: ['Kreativa Europa Desk Sverige','Filmhuset'],
    cast: ['Pella Kågerman','Hugo Lilja','Sara Bergmark Elfgren','Jan Göransson'],
    date: '2019-09-19',
  },
];

module.exports = Audio