const Video = [

  {
    id: 129,
    order: '3',
    type: 'video',
    playlists: 'Masterclass med Pia Olby',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'Nmf2V55mlgw',
    thumb_url: 'https://i.ytimg.com/vi/Nmf2V55mlgw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAOexoLm8VvzJpjHvNaK2wt8jcDTA',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby vad skönsång är för henne.',
    short_description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella...',
    tags: ['Sång','Musik','Scenkonst','Teater','Masterclass'],
    title: 'Masterclass med Pia Olby - Vad är skönsång (del 3 av 4)',
    short_title: 'Masterclass med Pia Olby (del 3 av 4)',
    collaborators: ['Teateralliansen','Kulturakademin'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 128,
    order: '1',
    type: 'video',
    playlists: 'Masterclass med Pia Olby',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'OO-v7--wOtU',
    thumb_url: 'https://i.ytimg.com/vi/OO-v7--wOtU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCqnNF7TcOkq5fiXSXVP5wwLpnC6g',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby begreppet sånggestaltning.',
    short_description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella...',
    tags:['Sång','Musik','Scenkonst','Teater ','Masterclass'],
    title: 'Masterclass med Pia Olby - Vad är sånggestaltning (del 1 av 4)',
    short_title: 'Masterclass med Pia Olby (del 1 av 4)',
    collaborators: ['Teateralliansen','Kulturakademin'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 127,
    order: '2',
    type: 'video',
    playlists: 'Masterclass med Pia Olby',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'qgjKQrgL0o0',
    thumb_url: 'https://i.ytimg.com/vi/qgjKQrgL0o0/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCRHpUbj3sdAppiBn3hQxvLo9YWBg',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby skillnaden mellan textgestaltning och sånggestaltning.',
    short_description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella...',
    tags: ['Kulturakademin','Teateralliansen','Pia Olby','Textgestaltning','Sånggestaltning','K-play','Göteborg','Kurs','Skådespelare','Sång','Masterclass','webcast','learning'],
    title: 'Masterclass med Pia Olby - Textgestaltning (del 2 av 4)',
    short_title: 'Masterclass med Pia Olby (del 2 av 4)',
    collaborators: ['Teateralliansen','Kulturakademin'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 126,
    order: '4',
    type: 'video',
    playlists: 'Masterclass med Pia Olby',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'l2vcqaClw-A',
    thumb_url: 'https://i.ytimg.com/vi/l2vcqaClw-A/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAN72cgcdprjb9rzoU4UQFy2IEP5Q',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby kroppens betydelse i sång.',
    short_description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella...',
    tags: ['Sång','Musik','Scenkonst','Teater','Masterclass'],
    title: 'Masterclass med Pia Olby - Kroppens betydelse i sång (del 4 av 4)',
    short_title: 'Masterclass med Pia Olby (del 4 av 4)',
    collaborators: ['Teateralliansen','Kulturakademin'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 125,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'yGkn5KYk6sg',
    thumb_url: 'https://i.ytimg.com/vi/yGkn5KYk6sg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCT1bHej_cH660mkGIoTd3vNHanEg',
    description: 'Rikke Ennis, CEO Reinvent Studios, Helene Aurø, Sales and Marketing Director Reinvent Studios. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'Rikke Ennis, CEO Reinvent Studios, Helene Aurø, Sales and Marketing Director Reinvent...',
    tags: ['TV Drama Vision','Produktion','Film','Marknadsföring'],
    title: 'NEW ON THE MAP: REInvent Studios',
    short_title: 'NEW ON THE MAP: REInvent Studios',
    collaborators: ['Göteborg Film Festival','REInvent Studios'],
    cast: ['Rikke Ennis','Helene Aurø'],
    date: '2019-03-11',
  },
  {
    id: 124,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'qvWzFtNPbB4',
    thumb_url: 'https://i.ytimg.com/vi/qvWzFtNPbB4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBwQwXEsEZub3mawzcUO856sERrEQ',
    description: 'Meet Netflix´s Lina Bronéus, Drirector of Co-Productions & Acquisitions, in a keynote talk about the growing importance of the international markets for Netflix and the company´s plans for the Nordics. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'Meet Netflix´s Lina Bronéus, Drirector of Co-Productions & Acquisitions, in a keynote...',
    tags: ['TV Drama Vision','TV', 'Kommunikation & Samarbete','Politik','Föreläsning', ],
    title: 'NETFLIX´S AMBITIONS FOR THE NORDIC REGION: Lina Bronéus',
    short_title: 'NETFLIX´S AMBITIONS FOR THE NORDIC REGION: Lina Bronéus',
    collaborators: ['Göteborg Film Festival','NETFLIX'],
    cast: ['Lina Bronéus'],
    date: '2019-03-08',
  },
  {
    id: 123,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'uRkfLsPntFY',
    thumb_url: 'https://i.ytimg.com/vi/uRkfLsPntFY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAsFnTmXhRoB53neovDq6BPYgk4fA',
    description: 'Meet two of Italy´s top producers, Nicola Serra, Managing Director of Palomar and Marco Chimenz, Co-CEO of Cattleya, talking about their upcoming slates, trends in Italian drama and the new tv series The Name of the Rose. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'Meet two of Italy´s top producers, Nicola Serra, Managing Director of Palomar and Marco...',
    tags: ['TV Drama Vision','TV','Drama','Trend','Produktion','Engelska'],
    title: 'SPOTLIGHT ON ITALY: Nicola Serra from Palomar and Marco Chimenz from Cattleya',
    short_title: 'SPOTLIGHT ON ITALY',
    collaborators: ['Göteborg Film Festival','Palomar','Cattleya'],
    cast: ['Nicola Serra','Marco Chimenz'],
    date: '2019-03-07',
  },
  {
    id: 122,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'ylK-RNFy2wo',
    thumb_url: 'https://i.ytimg.com/vi/ylK-RNFy2wo/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDuOACW5pt6rZDTuOWfOoaltpYcIA',
    description: 'Speaker: Niclas Ekström, screenwriter and project manager, The Script Factory. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'peaker: Niclas Ekström, screenwriter and project manager, The Script Factory. Moderator:...',
    tags: ['TV Drama Vision','Film','TV','Genre','Engelska'],
    title: 'THE SCRIPT FACTORY INTRODUCES THE COMEDY LAB',
    short_title: 'THE SCRIPT FACTORY INTRODUCES THE COMEDY LAB',
    collaborators: ['Göteborg Film Festival','The Script Factory'],
    cast: ['Niclas Ekström'],
    date: '2019-03-07',
  },
  {
    id: 121,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: '-lZxocIB8GA',
    thumb_url: 'https://i.ytimg.com/vi/-lZxocIB8GA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBl_L8PrruQpd2-EeLyC_fnzUHnuA',
    description: 'Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Presented in collaboration with Kulturakademin and MediaXchange Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision”...',
    tags: ['TV Drama Vision','Film','TV','Genre','Engelska'],
    title: 'JON PLOWMAN ON HOW TO CREATE GOOD COMEDY AND WHY WE NEED LESS DRAMA',
    short_title: 'JON PLOWMAN ON HOW TO CREATE GOOD COMEDY',
    collaborators: ['Göteborg Film Festival','Kulurakademin','MediaXchange'],
    cast: ['Jon Plowman','Wendy Mitchell'],
    date: '2019-03-06',
  },
  {
    id: 120,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'tzZXIyfk8n8',
    thumb_url: 'https://i.ytimg.com/vi/tzZXIyfk8n8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBwms2EHLX64P1-5NPywRsuvdMe3g',
    description: 'FROM THE NORDICS TO EUROPE TO THE WORLD Liselott Forsman, Executive Producer of International Drama at YLE and the Head of Fiction Experts at EBU (The European Broadcasting Union) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'FROM THE NORDICS TO EUROPE TO THE WORLD Liselott Forsman, Executive Producer of International...',
    tags: ['K-play','Kulturakademin','Göteborg Film Festival 2019','TV Drama Vision','Liselott Forsman','YLE','Broadcasters','EBU','The European Broadcasting Union','Drama','Fiction','TV','Film','Webcast','webcast','learning'],
    title: 'THE BROADCASTERS´ POINT OF VIEW WITH LISELOTT FORSMAN (International Drama at YLE)',
    short_title: 'THE BROADCASTERS´ POINT OF VIEW',
    collaborators: ['Göteborg Film Festival','The European Broadcasting Union'],
    cast: ['Liselott Forsman','Wendy Mitchell'],
    date: '2019-03-04',
  },
  {
    id: 119,
    order: '6',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision','Nominated Writers'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'QM2T14Shc0g',
    thumb_url: 'https://i.ytimg.com/vi/QM2T14Shc0g/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAC8w1MKw7gj5fQGj9fdTAwkrSZlg',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Mette.M.Bølstad (State of Happiness, Norway) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference TV Drama Vision Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Mette.M.Bølstad...',
    tags: ['TV Drama Vision','Nominated Writers','Manus','Storytelling','Intervju','TV','Film','Produktion','Engelska'],
    title: 'NOMINATED WRITERS – Mette M Bølstad (State of Happiness, Norway)',
    short_title: 'NOMINATED WRITERS – Mette M Bølstad',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Mette M. Bølstad','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 118,
    order: '5',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision','Nominated Writers'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'm2OIPCroyvk',
    thumb_url: 'https://i.ytimg.com/vi/m2OIPCroyvk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD2JYFStWSbWmnFjmuYVPKEjyHgzg',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Claudia Boderke, Lars Mering (The New Nurses, Danmark) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference TV Drama Vision Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    short_description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Claudia Boderke, Lars Mering...',
    tags: ['TV Drama Vision','Nominated Writers','Manus','Storytelling','Intervju','TV','Film','Produktion','Engelska'],
    title: 'NOMINATED WRITERS – Claudia Boderke, Lars Mering (The New Nurses, Danmark)',
    short_title: 'NOMINATED WRITERS – Claudia Boderke, Lars Mering',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Claudia Boderke','Lars Mering','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 117,
    order: '4',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision','Nominated Writers'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: '2eDYHYWUxU4',
    thumb_url: 'https://i.ytimg.com/vi/2eDYHYWUxU4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBWc5C5EsTUZElDPhj0sqBJTkUtdQ',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Håkan Lindhé (The Inner Circle, Sweden) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    short_description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Håkan Lindhé (The Inner Circle...',
    tags: ['TV Drama Vision','Nominated Writers','Manus','Storytelling','Intervju','TV','Film','Produktion','Engelska'],
    title: 'NOMINATED WRITERS – Håkan Lindhé (The Inner Circle, Sweden)',
    short_title: 'NOMINATED WRITERS – Håkan Lindhé',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Håkan Lindhé','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 116,
    order: '3',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision','Nominated Writers'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'j3cNkxmhrDk',
    thumb_url: 'https://i.ytimg.com/vi/j3cNkxmhrDk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCBYp9jAV9SjyzphjtJG7tdmF6r4A',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Patrik Syversen, Jesper Sundnes, Stig Frode Henriksen (Kieler Street, Norway) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    short_description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Patrik Syversen, Jesper Sundnes...',
    tags: ['TV Drama Vision','Nominated Writers','Manus','Storytelling','Intervju','TV','Film','Produktion','Engelska'],
    title: 'NOMINATED WRITERS – Patrik Syversen, Jesper Sundnes, Stig Frode Henriksen (Kieler Street, Norway)',
    short_title: 'NOMINATED WRITERS – Patrik, Jesper, Stig',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Patrik Syversen','Jesper Sundnes','Stig Frode Henriksen','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 115,
    order: '2',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision','Nominated Writers'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'V_oSKSC2l-w',
    thumb_url: 'https://i.ytimg.com/vi/V_oSKSC2l-w/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBlRBCnkjNa8KdDP9Yu_MXaIHaGrg',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Margrét Örnólfdóttir (The Flatey Enigma, Iceland) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    short_description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Margrét Örnólfdóttir...',
    tags: ['TV Drama Vision','Nominated Writers','Manus','Storytelling','Intervju','TV','Film','Produktion','Engelska'],
    title: 'NOMINATED WRITERS – Margrét Örnólfdóttir (The Flatey Enigma, Iceland)',
    short_title: 'NOMINATED WRITERS – Margrét Örnólfdóttir',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Margrét Örnólfdóttir','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 114,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision','Nominated Writers'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'lfyp0qF36VU',
    thumb_url: 'https://i.ytimg.com/vi/lfyp0qF36VU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCCY0fSwl71tkeQ3wDCb4Dr1c3lAA',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Mika Ronkainen, Merja Aakko (All the Sins, Finland) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival.  Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    short_description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Mika Ronkainen...',
    tags: ['TV Drama Vision','Nominated Writers','Manus','Storytelling','Intervju','TV','Film','Produktion','Engelska'],
    title: 'NOMINATED WRITERS – Mika Ronkainen, Merja Aakko (All the Sins, Finland)',
    short_title: 'NOMINATED WRITERS – Mika Ronkainen, Merja Aakko',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Mika Ronkainen','Merja Aakko','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 113,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'UmGkHDYJRk4',
    thumb_url: 'https://i.ytimg.com/vi/UmGkHDYJRk4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAnx40LKxyQXHYcLiDJ2oiSrtZ7Pg',
    description: 'Multi award winning British television writer, producer and director Sally Wainwright (Happy Valley, Last Tango in Halifax) on her career and the art of writing. Moderator: Wendy Mitchell Photo and video editing - Leif Eriksson Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin in collaboration with Göteborg Film Festival, SVT and MediaXchange',
    short_description: 'Multi award winning British television writer, producer and director Sally Wainwright...',
    tags: ['TV Drama Vision','TV','Manus','Produktion','Regi','Storytelling','Audition & Ansökningar'],
    title: 'TV DRAMA VISION 2019: Sally Wainwright - big ideas in small towns',
    short_title: 'TV DRAMA VISION 2019: Sally Wainwright',
    collaborators: ['Göteborg Film Festival','SVT','MediaXchange'],
    cast: ['Sally Wainwright','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 112,
    order: '2',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','The Nostradamus Report','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: '744CLQ_OqTI',
    thumb_url: 'https://i.ytimg.com/vi/744CLQ_OqTI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDDqICjR-8PpQN4__RVQir-kW4j0w',
    description: 'The presentation of the 6th report at Göteborg Film Festival February 1 was followed by a discussion with Tomas Eskilsson, Head of Strategy, Film i Väst; Maria Tanjala, Co-Founder, Big Couch and Film Chain; and Glenn O’Farrell, CEO, GroupeMédia TFO. Photo and video editing - Leif Eriksson',
    short_description: 'The presentation of the 6th report at Göteborg Film Festival February 1 was followed by...',
    tags: ['Film','TV','Finans & Bidrag','Produktion','Trend','Teknik','Engelska'],
    title: 'The 6th Nostradamus Report - Discussion (part 2 of 2)',
    short_title: 'The 6th Nostradamus Report - Discussion (part 2 of 2)',
    collaborators: ['Göteborg Film Festival','Film i Väst','Big Couch','GroupeMédia TFO','Nostradamus'],
    cast: ['Tomas Eskilsson','Maria Tanjala','Glenn O’Farrell'],
    date: '2019-02-05',
  },
  {
    id: 111,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','The Nostradamus Report','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'Ulxy5bL_Ivg',
    thumb_url: 'https://i.ytimg.com/vi/Ulxy5bL_Ivg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDr68ppUQVfQ3FxOTQHOcp9sf1U3g',
    description: 'This year’s report, ”Relevance in a New Reality”, discusses the uncertain future of public funding, major movements on the streaming market, the role of cinema in the new value chain, potential paths forward for VR, and the need for a rebooted industry conversation around tech and shared challenges. Photo and video editing - Leif Eriksson',
    short_description: 'This year’s report, ”Relevance in a New Reality”, discusses the uncertain future of public...',
    tags: ['Film','TV','Finans & Bidrag','Produktion','Trend','Teknik','Bransch','Engelska'],
    title: 'The 6th Nostradamus Report ”Relevance in a New Reality” - Johanna Koljonen (part 1 of 2)',
    short_title: 'The 6th Nostradamus Report - Relevance in.. (part 1 of 2)',
    collaborators: ['Göteborg Film Festival','Nostradamus'],
    cast: ['Johanna Koljonen'],
    date: '2019-02-05',
  },
  {
    id: 110,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'cH7u1wazvmk',
    thumb_url: 'https://i.ytimg.com/vi/cH7u1wazvmk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBbaR20Q7hVsYglwngu7FbB0uIndg',
    description: 'The legendary british BBC producer Jon Plowman is the man behind humorous, innovative successes like Absolutely Fabulous, The Office and Extras. Over a career spanning nearly 40 years he has learned everything there is to know about TV comedy and has, moreover, written a book about it: “How to Produced Comedy Bronze.” Plowman will be collaborating at the festival’s industry event, TV Drama Vision, but will also make this unique, public appearance at Festivalarenan. The program item is a cooperation with Kulturakademin. Moderator: Neta Norrmo, culture journalist. Photo and video editing - Leif Eriksson',
    short_description: 'The legendary british BBC producer Jon Plowman is the man behind humorous, innovative...',
    tags: ['TV','Finans & Bidrag','Produktion','Trend','Teknik','Bransch','Engelska'],
    title: 'Masterclass with Jon Plowman - How to produce comedy bronze',
    short_title: 'Masterclass with Jon Plowman - How to produce comedy bronze',
    collaborators: ['Göteborg Film Festival','Kulturakademin'],
    cast: ['Jon Plowman','Neta Norrmo'],
    date: '2019-02-02',
  },
  {
    id: 109,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','The Nostradamus Report','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'ZRN02FV5KKo',
    thumb_url: 'https://i.ytimg.com/vi/ZRN02FV5KKo/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBAXMg_2frFVteQPnF3WE8c-fUcaQ',
    description: 'Nostradamus @ TV Drama Vision: Streaming Shapes the Landscape. Change in the world of episodic drama is accelerating thanks to the global expansion of the mega platforms, shifting fortunes at public broadcasters, and local streaming services on the rise. At Nostradamus’ session during TV Drama Vision the report’s analyst and writer Johanna Koljonen will give us highlights from the upcoming report. Presented by Göteborg Film Festival with support from Lindholmen Science Park, Region Västra Götaland, Nordisk Film & TV Fond and Kulturakademin. Photo and video editing - Leif Eriksson',
    short_description: 'Nostradamus @ TV Drama Vision: Streaming Shapes the Landscape. Change in the world...',
    tags: ['Film','TV','Finans & Bidrag','Produktion','Trend','Teknik','Bransch','Engelska'],
    title: 'TV DRAMA VISION 2019: Nostradamus @ TV Drama Vision: Streaming Shapes the Landscape',
    short_title: 'TV DRAMA VISION 2019: Nostradamus',
    collaborators: ['Göteborg Film Festival','Lindholmen Science Park','Region Västra Götaland','Nordisk Film & TV Fond','Kulturakademin','Nostradamus'],
    cast: ['Johanna Koljonen'],
    date: '2019-01-30',
  },
  {
    id: 108,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'eYVU04XHop8',
    thumb_url: 'https://i.ytimg.com/vi/eYVU04XHop8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDifHaZgsOSSdc_KrLYZemuGZ9oYg',
    description: 'The Art of Writing for Television - the leap from book to script. Targeting the creative process of storytelling in episodic drama, we meet the acclaimed Swedish writers Malin Giolito, Johannes Anyuru, Helena von Zweigberk for the first time entering the world of television after participating in SVT’s 12-month writing programme. Moderator: Marit Kapla, journalist Photo and video editing - Leif Eriksson',
    short_description: 'The Art of Writing for Television - the leap from book to script. Targeting...',
    tags: ['Film','TV','Finans & Bidrag','Produktion','Trend','Teknik','Bransch','Engelska'],
    title: 'TV DRAMA VISION 2019: The Art of Writing for Television - the leap from book to script',
    short_title: 'TV DRAMA VISION 2019: The Art of Writing for Television',
    collaborators: ['TV Drama Vision 2019'],
    cast: ['Malin Giolito','Johannes Anyuru','Helena von Zweigberk','Marit Kapla'],
    date: '2019-01-30',
  },
  {
    id: 107,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2019','TV Drama Vision'],
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: 'XDXQLTP3Yn8',
    thumb_url: 'https://i.ytimg.com/vi/XDXQLTP3Yn8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAEVAxWjoMg89tlpmo-g9WHxR8SpQ',
    description: 'Welcome and introduction by Cia Edström, Head of TV Drama Vision, Wendy Mitchell, moderator. Nordisk Film & TV Fond Prize: Meet the jury. Hear more about this year’s nominated series and get to know our amazing jury. Petri Kemppinen, CEO Nordisk Film & TV Fond, Cia Edström, Head of TV Drama Vision Laura Birn, actress, Christina Jeurling Birro, journalist, Alexander Karim, actor, and Justin Judd, producer. Photo and video editing - Leif Eriksson',
    short_description: 'Welcome and introduction by Cia Edström, Head of TV Drama Vision, Wendy Mitchell...',
    tags: ['Film','TV','Trend','Teknik','Bransch','Engelska'],
    title: 'TV DRAMA VISION 2019: Introduction/Nordisk Film & TV Fond Prize: Meet the jury',
    short_title: 'TV DRAMA VISION 2019: Introduction/Nordisk..',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond'],
    cast: ['Petri Kemppinen','Cia Edström','Laura Birn','Christina Jeurling Birro','Alexander Karim','Justin Judd'],
    date: '2019-01-30',
  },
  {
    id: 106,
    order: '1',
    type: 'video',
    playlists: 'Göteborg Film Festival 2019',
    categories: ['allt','film&tv'],
    level: 'Samtal',
    media_id: '_BhiH3GG8pI',
    thumb_url: 'https://i.ytimg.com/vi/_BhiH3GG8pI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDvssgalwzIq2kAEmsBOyF9TATr9w',
    description: 'Olle Tholén från filmkollektivet Crazy Pictures ser tillbaka på det kollektiva arbetet med den första långfilmen "Den blomster tid nu kommer". Föreläsningen pågår till 30 min och 30 sek, därefter följer ett samtal med moderator Karin Ekberg, regissör, manusförfattare och producent. Föreläsningen är ett samarbete mellan Kulturakademin och Göteborg Filmfestival 2019. Photo and video editing - Leif Eriksson',
    short_description: 'Olle Tholén från filmkollektivet Crazy Pictures ser tillbaka på det kollektiva...',
    tags: ['Film','Bransch','Produktion','Regi','Storytelling','Manus','Teknik','Kommunikation & Samarbete','Finans & bidrag'],
    title: 'FÖRELÄSNING/SAMTAL: Den blomster tid nu kommer – ett halvår senare.',
    short_title: 'FÖRELÄSNING/SAMTAL: Den blomster tid nu kommer',
    collaborators: ['Göteborg Filmfestival 2019','Crazy Pictures','Kulturakademin'],
    cast: ['Olle Tholén','Karin Ekberg'],
    date: '2019-01-27',
  },
  {
    id: 105,
    order: '1',
    type: 'video',
    playlists: 'Musik för Barn',
    categories: ['allt','musik'],
    level: 'Samtal',
    media_id: 'DyTBdvHvrbA',
    thumb_url: 'https://i.ytimg.com/vi/DyTBdvHvrbA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB54VI3t4KEJSjT62o41KbmvUvVgg',
    description: 'Stråf Vocal Strings framför en del av sin föreställning Familia samt berättar om sin arbetsprocess och hur de möter den unga publiken. Stråf Vocal Strings består av Sanna Källman, Tobias Edvardsson, Francis Schaughnessy och Åsa Johansson. Photo and video editing - Leif Eriksson Producerat av Kulturakademin i samarbete med Kultur i Väst, Musikalliansen, Kulturförvaltningen Göteborg och Musikcentrum Väst',
    short_description: 'Stråf Vocal Strings framför en del av sin föreställning Familia samt berättar...',
    tags: ['Musik','Kompositör','Barn & Unga','Kommunikation & Samarbete','Instrument'],
    title: 'Stråf Vocal Strings - Att spela för en ung publik',
    short_title: 'Stråf Vocal Strings - Att spela för en ung publik',
    collaborators: ['Stråf Vocal Strings','Kultur i Väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum'],
    cast: ['Sanna Källman','Tobias Edvardsson','Francis Schaughnessy','Åsa Johansson'],
    date: '2018-11-26',
  },
  {
    id: 104,
    order: '1',
    type: 'video',
    playlists: 'Musik för Barn',
    categories: ['allt','musik'],
    level: 'Samtal',
    media_id: 'qIyf8foXliQ',
    thumb_url: 'https://i.ytimg.com/vi/qIyf8foXliQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB1LIpLM8AJsGvbp1KOefGsBcj3PA',
    description: 'Vilka bidragssystem finns i Göteborgs stad och Västra Götalandsregionen för att spela för en ung publik? Och på vilka plattformar finns möjlighet att synas? Information från Helena Rung från Kultur i Väst och Ida Kaivola från Göteborgs Kulturförvaltning. Photo and video editing - Leif Eriksson Producerat av Kulturakademin i samarbete med Kultur i Väst, Musikalliansen, Kulturförvaltningen Göteborg och Musikcentrum Väst www.kulturakademin.com',
    short_description: 'Vilka bidragssystem finns i Göteborgs stad och Västra Götalandsregionen för att...',
    tags: ['Musik','Kompositör','Barn & Unga','Kommunikation & Samarbete','Instrument'],
    title: 'Om synlighet och bidragssystem för musiker som spelar för en ung publik',
    short_title: 'Om synlighet och bidragssystem',
    collaborators: ['Kultur i Väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum Väst'],
    cast: ['Helena Rung','Ida Kaivola'],
    date: '2018-11-26',
  },
  {
    id: 103,
    order: '1',
    type: 'video',
    playlists: 'Musik för Barn',
    categories: ['allt','musik'],
    level: 'Samtal',
    media_id: 'JxEAzfezxbY',
    thumb_url: 'https://i.ytimg.com/vi/JxEAzfezxbY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBAJa40TAxVxpLFDMogkXwiqFVZLw',
    description: 'Producentbyråns Julia Sjönneby tipsar om de bästa sätten för musiker som spelar för en ung publik att marknadsföra sig och kommunicera med arrangörer. Photo and video editing - Leif Eriksson Producerat av Kulturakademin i samarbete med Kultur i Väst, Musikalliansen, Kulturförvaltningen Göteborg och Musikcentrum Väst. www.kulturakademin.com',
    short_description: 'Producentbyråns Julia Sjönneby tipsar om de bästa sätten för musiker som spelar...',
    tags: ['Musik','Kompositör','Barn & Unga','Kommunikation & Samarbete','Instrument'],
    title: 'Flertal tips för musiker som spelar för en ung publik',
    short_title: 'Flertal tips för musiker',
    collaborators: ['Kultur i Väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum Väst'],
    cast: ['Julia Sjönneby'],
    date: '2018-11-26',
  },
  {
    id: 102,
    order: '1',
    type: 'video',
    playlists: ['Göteborg Film Festival 2018','Audiovisual Days 2018'],
    categories: ['allt','scenteknik'],
    level: 'Samtal',
    media_id: 'uyJKlhOsf3s',
    thumb_url: 'https://i.ytimg.com/vi/uyJKlhOsf3s/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDIOyMXL-TvFi2RdC7nyCr04ZYVpA',
    description: 'Moderator: Johanna Koljonen, redaktör Nostradamus. Panel: Petri Kemppinen, CEO Nordisk Film & TV Fond, Tatjana Samopjan, Creative Development Producer, Martina Österling, Agent Albatros Agency. Efter flera år av stora förändringar med nya affärsmodeller, publikbeteenden och tekniska innovationer är TV Drama-branschen fortfarande i omvälvning. Lyssna till våra inbjudna experter när de ger deras syn på framtidens dramaserier; innehåll, finansiering och vad man bör tänka på när man utvecklar sitt projekt. Photo and video editing - Leif Eriksson',
    short_description: 'Moderator: Johanna Koljonen, redaktör Nostradamus. Panel: Petri Kemppinen...',
    tags: ['TV','Film','Bransch','Storytelling','Produktion','Finans & Bidrag','Trend','Hållbarhet'],
    title: 'AUDIOVISUAL DAYS 2018: Panelsamtal: "På spaning efter framtidens dramaserier"',
    short_title: 'AUDIOVISUAL DAYS 2018: Panelsamtal:',
    collaborators: ['Göteborg Film Festival','Nordisk Film & TV Fond','Albatros Agency','Nostradamus'],
    cast: ['Johanna Koljonen','Petri Kemppinen','Tatjana Samopjan','Martina Österling'],
    date: '2018-10-18',
  },
  {
    id: 101,
    order: '2',
    type: 'video',
    playlists: ['Göteborg Film Festival 2018','Audiovisual Days 2018'],
    categories: ['allt','scenteknik'],
    level: 'Samtal',
    media_id: 'arPKOLILtkk',
    thumb_url: 'https://i.ytimg.com/vi/arPKOLILtkk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLClrmOupUii5RZzvcCYKWaCc4jLDg',
    description: 'Den femte Nostradamus-rapporten med den utmanande titeln ”Do or Die?” presenterades under Göteborg Film Festival 2018. Här ger rapportens författare Johanna Koljonen en uppdaterad föreläsning som bland annat tar upp vad som kommer krävas av den europeiska filmbranschen de närmaste åren för att konkurrera på en global marknad i ständig förändring. Photo and video editing - Leif Eriksson',
    short_description: 'Den femte Nostradamus-rapporten med den utmanande titeln ”Do or Die?...',
    tags: ['TV','Film','Bransch','Storytelling','Produktion','Finans & Bidrag','Trend','Hållbarhet'],
    title: 'AUDIOVISUAL DAYS 2018: Johanna Koljonen "Do or die"',
    short_title: 'AUDIOVISUAL DAYS 2018: Johanna Koljonen',
    collaborators: ['Göteborg Film Festival', 'Nostradamus',],
    cast: ['Johanna Koljonen'],
    date: '2018-10-18',
  },
];

module.exports = Video;