const Video = [

  {
    id: 129,
    order: '3',
    type: 'video',
    playlist: '1',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'Nmf2V55mlgw',
    thumb_url: 'https://i.ytimg.com/vi/Nmf2V55mlgw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAOexoLm8VvzJpjHvNaK2wt8jcDTA',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby vad skönsång är för henne.',
    tags: ['Kulturakademin','Teateralliansen','Pia Olby','Textgestaltning','Sånggestaltning','Skönsång','K-play','Göteborg','Kurs','Skådespelare','Sång','Masterclass','webcast','learning'],
    // title: 'Masterclass med Pia Olby - Vad är skönsång (del 3 av 4)',
    title: 'Masterclass med Pia Olby (Del 3 av 4)',
    collaborators: ['Teateralliansen'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 128,
    order: '1',
    type: 'video',
    playlist: '1',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'OO-v7--wOtU',
    thumb_url: 'https://i.ytimg.com/vi/OO-v7--wOtU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCqnNF7TcOkq5fiXSXVP5wwLpnC6g',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby begreppet sånggestaltning.',
    tags: ['Kulturakademin','Teateralliansen','Pia Olby','Sånggestaltning','K-play','Göteborg','Kurs','Skådespelare','Sång','Masterclass','webcast','learning'],
    title: 'Masterclass med Pia Olby - Vad är sånggestaltning (del 1 av 4)',
    collaborators: ['Teateralliansen'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 127,
    order: '2',
    type: 'video',
    playlist: '1',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'qgjKQrgL0o0',
    thumb_url: 'https://i.ytimg.com/vi/qgjKQrgL0o0/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCRHpUbj3sdAppiBn3hQxvLo9YWBg',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby skillnaden mellan textgestaltning och sånggestaltning.',
    tags: ['Kulturakademin','Teateralliansen','Pia Olby','Textgestaltning','Sånggestaltning','K-play','Göteborg','Kurs','Skådespelare','Sång','Masterclass','webcast','learning'],
    title: 'Masterclass med Pia Olby - Textgestaltning och sånggestaltning (del 2 av 4)',
    collaborators: ['Teateralliansen'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 126,
    order: '4',
    type: 'video',
    playlist: '1',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'l2vcqaClw-A',
    thumb_url: 'https://i.ytimg.com/vi/l2vcqaClw-A/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAN72cgcdprjb9rzoU4UQFy2IEP5Q',
    description: 'Kulturakademin och Teateralliansens kursen i sånggestaltning erbjuder professionella skådespelare möjlighet att arbeta med och utveckla sin egen vokala och musikaliska potential - och att utmana sig själva sångmässigt. Här förklarar kursledare Pia Olby kroppens betydelse i sång.',
    tags: ['Kulturakademin','Teateralliansen','Pia Olby','Kroppens betydelse','Textgestaltning','Sånggestaltning','Skönsång','K-play','Göteborg','Kurs','Skådespelare','Sång','Masterclass','webcast','learning'],
    title: 'Masterclass med Pia Olby - Kroppens betydelse i sång (del 4 av 4)',
    collaborators: ['Teateralliansen'],
    cast: ['Pia Olby'],
    date: '2019-04-16',
  },
  {
    id: 125,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'yGkn5KYk6sg',
    thumb_url: 'https://i.ytimg.com/vi/yGkn5KYk6sg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCT1bHej_cH660mkGIoTd3vNHanEg',
    description: 'Rikke Ennis, CEO Reinvent Studios, Helene Aurø, Sales and Marketing Director Reinvent Studios. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Webcast','Göteborg Film Festival 2019','TV Drama Days 2019','REInvent Studios','Helene Aurø','Rikke Ennis','Wendy Mitchell','webcast','learning'],
    title: 'NEW ON THE MAP: REInvent Studios',
    collaborators: ['Göteborg Film Festival 2019'],
    cast: ['Rikke Ennis'],
    date: '2019-03-11',
  },
  {
    id: 124,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'qvWzFtNPbB4',
    thumb_url: 'https://i.ytimg.com/vi/qvWzFtNPbB4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBwQwXEsEZub3mawzcUO856sERrEQ',
    description: 'Meet Netflix´s Lina Bronéus, Drirector of Co-Productions & Acquisitions, in a keynote talk about the growing importance of the international markets for Netflix and the company´s plans for the Nordics. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Göteborg Film Festival 2019','TV Drama Days 2019','Netflix','Lina Bronéus','Nordic','Plans','Cenference','Wendy Mitchell','Ambitions','Learning','Education','webcast','learning'],
    title: 'NETFLIX´S AMBITIONS FOR THE NORDIC REGION: Lina Bronéus',
    collaborators: ['Göteborg Film Festival 2019'],
    cast: ['Lina Bronéus'],
    date: '2019-03-08',
  },
  {
    id: 123,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'uRkfLsPntFY',
    thumb_url: 'https://i.ytimg.com/vi/uRkfLsPntFY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAsFnTmXhRoB53neovDq6BPYgk4fA',
    description: 'Meet two of Italy´s top producers, Nicola Serra, Managing Director of Palomar and Marco Chimenz, Co-CEO of Cattleya, talking about their upcoming slates, trends in Italian drama and the new tv series The Name of the Rose. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['Nicola Serra','Palomar','Marco Chimenz','Cattleya','Italy','top producers','trends','drama','The Name of the Rose','K-PLAY','Kulturakademin','Webcast','Göteborg Film Festival 2019','TD Drama Vision 2019','Wendy Mitchell','Leif Eriksson','webcast','learning'],
    title: 'SPOTLIGHT ON ITALY: Nicola Serra from Palomar and Marco Chimenz from Cattleya',
    collaborators: ['Göteborg Film Festival 2019'],
    cast: ['Nicola Serra','Marco Chimenz'],
    date: '2019-03-07',
  },
  {
    id: 122,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'ylK-RNFy2wo',
    thumb_url: 'https://i.ytimg.com/vi/ylK-RNFy2wo/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDuOACW5pt6rZDTuOWfOoaltpYcIA',
    description: 'Speaker: Niclas Ekström, screenwriter and project manager, The Script Factory. Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Webcast','Kulturakademin','Göteborg Film Festival 2019','Manusfabriken','The Script Factory','Comedy Lab','TV Drama Vision 2019','Niclas Ekström','Screenwriter','Film','TV','webcast','learning'],
    title: 'THE SCRIPT FACTORY INTRODUCES THE COMEDY LAB',
    collaborators: ['Göteborg Film Festival 2019'],
    cast: ['Niclas Ekström'],
    date: '2019-03-07',
  },
  {
    id: 121,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '-lZxocIB8GA',
    thumb_url: 'https://i.ytimg.com/vi/-lZxocIB8GA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBl_L8PrruQpd2-EeLyC_fnzUHnuA',
    description: 'Moderator: Wendy Mitchell Recorded 2019-01-31 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Presented in collaboration with Kulturakademin and MediaXchange Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Webcast','Göteborg Film Festival 2019','Comedy','Jon Plowman','BBC','MediaXchange','Culture Academy','Wendy Mitchell','webcast','learning'],
    title: 'JON PLOWMAN ON HOW TO CREATE GOOD COMEDY AND WHY WE NEED LESS DRAMA',
    collaborators: ['Göteborg Film Festival 2019'],
    cast: ['Jon Plowman','Wendy Mitchell'],
    date: '2019-03-06',
  },
  {
    id: 120,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'tzZXIyfk8n8',
    thumb_url: 'https://i.ytimg.com/vi/tzZXIyfk8n8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBwms2EHLX64P1-5NPywRsuvdMe3g',
    description: 'FROM THE NORDICS TO EUROPE TO THE WORLD Liselott Forsman, Executive Producer of International Drama at YLE and the Head of Fiction Experts at EBU (The European Broadcasting Union) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference ”TV Drama Vision” Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['K-play','Kulturakademin','Göteborg Film Festival 2019','TV Drama Vision','Liselott Forsman','YLE','Broadcasters','EBU','The European Broadcasting Union','Drama','Fiction','TV','Film','Webcast','webcast','learning'],
    title: 'THE BROADCASTERS´ POINT OF VIEW WITH LISELOTT FORSMAN (International Drama at YLE)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Liselott Forsman','Wendy Mitchell'],
    date: '2019-03-04',
  },
  {
    id: 119,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'QM2T14Shc0g',
    thumb_url: 'https://i.ytimg.com/vi/QM2T14Shc0g/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAC8w1MKw7gj5fQGj9fdTAwkrSZlg',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Mette.M.Bølstad (State of Happiness, Norway) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference TV Drama Vision Göteborg Film Festival. Produced for K-PLAY by Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Göteborg Film Festival','TV Drama Vision 2019','NORDISK FILM \u0026 TV FOND PRIZE','Nominated Writers','Writers','Mette.M.Bølstad','State of Happiness','Norway','Wendy Mitchell','webcast','learning'],
    title: 'NOMINATED WRITERS – Mette M Bølstad (State of Happiness, Norway)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Mette.M.Bølstad','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 118,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'm2OIPCroyvk',
    thumb_url: 'https://i.ytimg.com/vi/m2OIPCroyvk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD2JYFStWSbWmnFjmuYVPKEjyHgzg',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Claudia Boderke, Lars Mering (The New Nurses, Danmark) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference TV Drama Vision Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Göteborg Film Festival 2019','NORDISK FILM \u0026 TV FOND PRIZE','TV Drama Vision 2019','Nominated Writers','Writers','Claudia Boderke','Lars Mering','The New Nurses','Danmark','Wendy Mitchell','webcast','learning'],
    title: 'NOMINATED WRITERS – Claudia Boderke, Lars Mering (The New Nurses, Danmark)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Claudia Boderke','Lars Mering','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 117,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '2eDYHYWUxU4',
    thumb_url: 'https://i.ytimg.com/vi/2eDYHYWUxU4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBWc5C5EsTUZElDPhj0sqBJTkUtdQ',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Håkan Lindhé (The Inner Circle, Sweden) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Göteborg Film Festival 2019','NORDISK FILM \u0026 TV FOND PRIZE','Nominated Writers','Writer','Håkan Lindhé','The Inner Circle','Sweden','Wendy Mitchell','TV Drama Vision 2019','webcast','learning'],
    title: 'NOMINATED WRITERS – Håkan Lindhé (The Inner Circle, Sweden)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Håkan Lindhé','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 116,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'j3cNkxmhrDk',
    thumb_url: 'https://i.ytimg.com/vi/j3cNkxmhrDk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCBYp9jAV9SjyzphjtJG7tdmF6r4A',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Patrik Syversen, Jesper Sundnes, Stig Frode Henriksen (Kieler Street, Norway) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Göteborg Film Festival 2019','TV Drama Vision 2019','NORDISK FILM \u0026 TV FOND PRIZE','Nominated Writers','Writers','Patrik Syversen','Jesper Sundnes','Stig Frode Henriksen','Kieler Street','Norway','Wendy Mitchell','webcast','learning'],
    title: 'NOMINATED WRITERS – Patrik Syversen, Jesper Sundnes, Stig Frode Henriksen (Kieler Street, Norway)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Patrik Syversen','Jesper Sundnes','Stig Frode Henriksen','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 115,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'V_oSKSC2l-w',
    thumb_url: 'https://i.ytimg.com/vi/V_oSKSC2l-w/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBlRBCnkjNa8KdDP9Yu_MXaIHaGrg',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Margrét Örnólfdóttir (The Flatey Enigma, Iceland) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    tags: ['K-PLAY','Kulturakademin','Göteborg Film Festival 2019','Nordisk Film \u0026 TV Fond Prize','Nominated Writers','Writers','Margrét Örnólfdóttir','The Flatey Enigma','Iceland','Wendy Mitchell','TV Drama Vision 2019','webcast','learning'],
    title: 'NOMINATED WRITERS – Margrét Örnólfdóttir (The Flatey Enigma, Iceland)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Margrét Örnólfdóttir','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 114,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'lfyp0qF36VU',
    thumb_url: 'https://i.ytimg.com/vi/lfyp0qF36VU/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCCY0fSwl71tkeQ3wDCb4Dr1c3lAA',
    description: 'NORDISK FILM & TV FOND PRIZE: MEET THE NOMINATED WRITERS – Mika Ronkainen, Merja Aakko (All the Sins, Finland) Moderator: Wendy Mitchell Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival.  Produced for K-PLAY by Kulturakademin Photo and video editing - Leif Eriksson',
    tags: ['K-play','Kulturakademin','Göteborg Film Festival 2019','Nordisk Film \u0026 TV Fond','Nominated Writers','Writers','Mika Ronkainen','Merja Aakko','All the sins','Finland','TV Drama Vision 2019','Wendy Mitchell','webcast','learning'],
    title: 'NOMINATED WRITERS – Mika Ronkainen, Merja Aakko (All the Sins, Finland)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Mika Ronkainen','Merja Aakko','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 113,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'UmGkHDYJRk4',
    thumb_url: 'https://i.ytimg.com/vi/UmGkHDYJRk4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAnx40LKxyQXHYcLiDJ2oiSrtZ7Pg',
    description: 'Multi award winning British television writer, producer and director Sally Wainwright (Happy Valley, Last Tango in Halifax) on her career and the art of writing. Moderator: Wendy Mitchell Photo and video editing - Leif Eriksson Recorded 2019-01-30 at the two-day conference "TV Drama Vision" Göteborg Film Festival. Produced for K-PLAY by Kulturakademin in collaboration with Göteborg Film Festival, SVT and MediaXchange',
    tags: ['K-play','Kulturakademin','Göteborg Film Festival 2019','Tv Drama Vision 2019','SVT','MediaXchange','Sally Wainwright','Happy Velly','Last Tango in Helifax','The art of writing','Writing','Television writer','Producer','Director','Wendy Mitchell','webcast','learning'],
    title: 'TV DRAMA VISION 2019: Sally Wainwright - big ideas in small towns',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Sally Wainwright','Wendy Mitchell'],
    date: '2019-02-22',
  },
  {
    id: 112,
    order: '2',
    type: 'video',
    playlist: '1',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: '744CLQ_OqTI',
    thumb_url: 'https://i.ytimg.com/vi/744CLQ_OqTI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDDqICjR-8PpQN4__RVQir-kW4j0w',
    description: 'The presentation of the 6th report at Göteborg Film Festival February 1 was followed by a discussion with Tomas Eskilsson, Head of Strategy, Film i Väst; Maria Tanjala, Co-Founder, Big Couch and Film Chain; and Glenn O’Farrell, CEO, GroupeMédia TFO. Photo and video editing - Leif Eriksson',
    tags: ['K-play','Kplay','Göteborg Film Festival','Kulturakademin','Nostradamus','Johanna Koljonen','Maria Tanjala','Glenn O’Farrell','Film i Väst','Big Couch and Film Chain','GroupeMédia TFO','webcast','learning'],
    title: 'The 6th Nostradamus Report - Discussion (part 2 of 2)',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Tomas Eskilsson','Maria Tanjala','Glenn O’Farrell'],
    date: '2019-02-05',
  },
  {
    id: 111,
    order: '1',
    type: 'video',
    playlist: '1',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'Ulxy5bL_Ivg',
    thumb_url: 'https://i.ytimg.com/vi/Ulxy5bL_Ivg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDr68ppUQVfQ3FxOTQHOcp9sf1U3g',
    description: 'This year’s report, ”Relevance in a New Reality”, discusses the uncertain future of public funding, major movements on the streaming market, the role of cinema in the new value chain, potential paths forward for VR, and the need for a rebooted industry conversation around tech and shared challenges. Photo and video editing - Leif Eriksson',
    tags: ['Johanna Koljonen','Nostradamus','Report','Göteborg Filmfestival','Kulturakademin','K-play','Kplay','Relevance in a new reality','Uncertain future','Public Funding','Streaming market','role of cinema','new value chain','VR','Industry','Conversation around tech','Shared Challenges','webcast','learning'],
    title: 'The 6th Nostradamus Report ”Relevance in a New Reality” - Johanna Koljonen (part 1 of 2)',
    collaborators: ['Nostradamus Report'],
    cast: ['Johanna Koljonen'],
    date: '2019-02-05',
  },
  {
    id: 110,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'cH7u1wazvmk',
    thumb_url: 'https://i.ytimg.com/vi/cH7u1wazvmk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBbaR20Q7hVsYglwngu7FbB0uIndg',
    description: 'The legendary british BBC producer Jon Plowman is the man behind humorous, innovative successes like Absolutely Fabulous, The Office and Extras. Over a career spanning nearly 40 years he has learned everything there is to know about TV comedy and has, moreover, written a book about it: “How to Produced Comedy Bronze.” Plowman will be collaborating at the festival’s industry event, TV Drama Vision, but will also make this unique, public appearance at Festivalarenan. The program item is a cooperation with Kulturakademin. Moderator: Neta Norrmo, culture journalist. Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'MASTERCLASS WITH JON PLOWMAN - HOW TO PRODUCE COMEDY BRONZE',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Jon Plowman','Neta Norrmo'],
    date: '2019-02-02',
  },
  {
    id: 109,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'ZRN02FV5KKo',
    thumb_url: 'https://i.ytimg.com/vi/ZRN02FV5KKo/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBAXMg_2frFVteQPnF3WE8c-fUcaQ',
    description: 'Nostradamus @ TV Drama Vision: Streaming Shapes the Landscape. Change in the world of episodic drama is accelerating thanks to the global expansion of the mega platforms, shifting fortunes at public broadcasters, and local streaming services on the rise. At Nostradamus’ session during TV Drama Vision the report’s analyst and writer Johanna Koljonen will give us highlights from the upcoming report. Presented by Göteborg Film Festival with support from Lindholmen Science Park, Region Västra Götaland, Nordisk Film & TV Fond and Kulturakademin. Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'TV DRAMA VISION 2019: Nostradamus @ TV Drama Vision: Streaming Shapes the Landscape',
    collaborators: ['Göteborg Film Festival'],
    cast: ['Johanna Koljonen'],
    date: '2019-01-30',
  },
  {
    id: 108,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'eYVU04XHop8',
    thumb_url: 'https://i.ytimg.com/vi/eYVU04XHop8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDifHaZgsOSSdc_KrLYZemuGZ9oYg',
    description: 'The Art of Writing for Television - the leap from book to script. Targeting the creative process of storytelling in episodic drama, we meet the acclaimed Swedish writers Malin Giolito, Johannes Anyuru, Helena von Zweigberk for the first time entering the world of television after participating in SVT’s 12-month writing programme. Moderator: Marit Kapla, journalist Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'TV DRAMA VISION 2019: The Art of Writing for Television - the leap from book to script',
    collaborators: ['TV Drama Vision 2019'],
    cast: ['Malin Giolito','Johannes Anyuru','Helena von Zweigberk','Marit Kapla'],
    date: '2019-01-30',
  },
  {
    id: 107,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','film&tv'],
    level: 'Masterclass',
    media_id: 'XDXQLTP3Yn8',
    thumb_url: 'https://i.ytimg.com/vi/XDXQLTP3Yn8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAEVAxWjoMg89tlpmo-g9WHxR8SpQ',
    description: 'Welcome and introduction by Cia Edström, Head of TV Drama Vision, Wendy Mitchell, moderator. Nordisk Film & TV Fond Prize: Meet the jury. Hear more about this year’s nominated series and get to know our amazing jury. Petri Kemppinen, CEO Nordisk Film & TV Fond, Cia Edström, Head of TV Drama Vision Laura Birn, actress, Christina Jeurling Birro, journalist, Alexander Karim, actor, and Justin Judd, producer. Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'TV DRAMA VISION 2019: Introduction/Nordisk Film & TV Fond Prize: Meet the jury',
    collaborators: ['TV Drama Vision 2019'],
    cast: ['Petri Kemppinen','Cia Edström','Laura Birn','Christina Jeurling Birro','Alexander Karim','Justin Judd'],
    date: '2019-01-30',
  },
  {
    id: 106,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt'],
    level: 'Masterclass',
    media_id: '_BhiH3GG8pI',
    thumb_url: 'https://i.ytimg.com/vi/_BhiH3GG8pI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDvssgalwzIq2kAEmsBOyF9TATr9w',
    description: 'Olle Tholén från filmkollektivet Crazy Pictures ser tillbaka på det kollektiva arbetet med den första långfilmen "Den blomster tid nu kommer". Föreläsningen pågår till 30 min och 30 sek, därefter följer ett samtal med moderator Karin Ekberg, regissör, manusförfattare och producent. Föreläsningen är ett samarbete mellan Kulturakademin och Göteborg Filmfestival 2019. Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'FÖRELÄSNING/SAMTAL: Den blomster tid nu kommer – ett halvår senare.',
    collaborators: ['Göteborg Filmfestival 2019'],
    cast: ['Olle Tholén','Karin Ekberg'],
    date: '2019-01-27',
  },
  {
    id: 105,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'DyTBdvHvrbA',
    thumb_url: 'https://i.ytimg.com/vi/DyTBdvHvrbA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB54VI3t4KEJSjT62o41KbmvUvVgg',
    description: 'Stråf Vocal Strings framför en del av sin föreställning Familia samt berättar om sin arbetsprocess och hur de möter den unga publiken. Stråf Vocal Strings består av Sanna Källman, Tobias Edvardsson, Francis Schaughnessy och Åsa Johansson. Photo and video editing - Leif Eriksson Producerat av Kulturakademin i samarbete med Kultur i Väst, Musikalliansen, Kulturförvaltningen Göteborg och Musikcentrum Väst',
    tags: ['Lärande','Utbildning','Kompetensutveckling','Stråf Vocal Strings','Musiker','musik','publik','live','gig','ung publik','Sanna Källman','Tobias Edvardsson','Francis Schaughnessy','Åsa Johansson','Kulturakademin','K-play','Kultur i väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum Väst','webcast','learning'],
    title: 'Stråf Vocal Strings - Att spela för en ung publik',
    collaborators: ['Stråf Vocal Strings'],
    cast: ['Sanna Källman','Tobias Edvardsson','Francis Schaughnessy','Åsa Johansson'],
    date: '2018-11-26',
  },
  {
    id: 104,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'qIyf8foXliQ',
    thumb_url: 'https://i.ytimg.com/vi/qIyf8foXliQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB1LIpLM8AJsGvbp1KOefGsBcj3PA',
    description: 'Vilka bidragssystem finns i Göteborgs stad och Västra Götalandsregionen för att spela för en ung publik? Och på vilka plattformar finns möjlighet att synas? Information från Helena Rung från Kultur i Väst och Ida Kaivola från Göteborgs Kulturförvaltning. Photo and video editing - Leif Eriksson Producerat av Kulturakademin i samarbete med Kultur i Väst, Musikalliansen, Kulturförvaltningen Göteborg och Musikcentrum Väst www.kulturakademin.com',
    tags: ['Lärande','Utbildning','Kulturakademin','Kultur i väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum Väst','Bidragssystem','Musiker','Musikbransch','publik','Ung publik','Helena Rung','Ida Kaivola','webcast','learning'],
    title: 'Om synlighet och bidragssystem för musiker som spelar för en ung publik',
    collaborators: ['Kultur i Väst','Göteborgs Kulturförvaltning'],
    cast: ['Helena Rung','Ida Kaivola'],
    date: '2018-11-26',
  },
  {
    id: 103,
    order: '1',
    type: 'video',
    playlist: '0',
    categories: ['allt','musik'],
    level: 'Masterclass',
    media_id: 'JxEAzfezxbY',
    thumb_url: 'https://i.ytimg.com/vi/JxEAzfezxbY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBAJa40TAxVxpLFDMogkXwiqFVZLw',
    description: 'Producentbyråns Julia Sjönneby tipsar om de bästa sätten för musiker som spelar för en ung publik att marknadsföra sig och kommunicera med arrangörer. Photo and video editing - Leif Eriksson Producerat av Kulturakademin i samarbete med Kultur i Väst, Musikalliansen, Kulturförvaltningen Göteborg och Musikcentrum Väst. www.kulturakademin.com',
    tags: ['Lärande','utbildning','Föreläsning','Musiker','Publik','Marknadsföring','Kommunikation','Arrangörer','Ung publik','Kulturakademin','Producentbyrån','Julia Sjönneby','Kultur i väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum Väst','webcast','learning'],
    title: 'Flertal tips för musiker som spelar för en ung publik',
    collaborators: ['Kultur i Väst','Musikalliansen','Kulturförvaltningen Göteborg','Musikcentrum Väst'],
    cast: ['Julia Sjönneby'],
    date: '2018-11-26',
  },
  {
    id: 102,
    order: '1',
    type: 'video',
    playlist: '1',
    categories: ['allt','scenteknik'],
    level: 'Masterclass',
    media_id: 'uyJKlhOsf3s',
    thumb_url: 'https://i.ytimg.com/vi/uyJKlhOsf3s/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDIOyMXL-TvFi2RdC7nyCr04ZYVpA',
    description: 'Moderator: Johanna Koljonen, redaktör Nostradamus. Panel: Petri Kemppinen, CEO Nordisk Film & TV Fond, Tatjana Samopjan, Creative Development Producer, Martina Österling, Agent Albatros Agency. Efter flera år av stora förändringar med nya affärsmodeller, publikbeteenden och tekniska innovationer är TV Drama-branschen fortfarande i omvälvning. Lyssna till våra inbjudna experter när de ger deras syn på framtidens dramaserier; innehåll, finansiering och vad man bör tänka på när man utvecklar sitt projekt. Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'AUDIOVISUAL DAYS 2018: Panelsamtal: "På spaning efter framtidens dramaserier"',
    collaborators: ['Nordisk Film & TV Fond','Albatros Agency'],
    cast: ['Johanna Koljonen','Petri Kemppinen','Tatjana Samopjan','Martina Österling'],
    date: '2018-10-18',
  },
  {
    id: 101,
    order: '2',
    type: 'video',
    playlist: '1',
    categories: ['allt','scenteknik'],
    level: 'Masterclass',
    media_id: 'arPKOLILtkk',
    thumb_url: 'https://i.ytimg.com/vi/arPKOLILtkk/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLClrmOupUii5RZzvcCYKWaCc4jLDg',
    description: 'Den femte Nostradamus-rapporten med den utmanande titeln ”Do or Die?” presenterades under Göteborg Film Festival 2018. Här ger rapportens författare Johanna Koljonen en uppdaterad föreläsning som bland annat tar upp vad som kommer krävas av den europeiska filmbranschen de närmaste åren för att konkurrera på en global marknad i ständig förändring. Photo and video editing - Leif Eriksson',
    tags: ['webcast','learning'],
    title: 'AUDIOVISUAL DAYS 2018: Johanna Koljonen "Do or die"',
    collaborators: ['Audiovisual days 2018'],
    cast: ['Johanna Koljonen'],
    date: '2018-10-18',
  },
];

module.exports = Video;